(c) pea under (&): "p_"
 zero one two : ".012"
 one five : ".15"
dos back acts &: "\acts"
dos back acts back &: "\acts\"
dos back gfc 400 &: "\gfc400\"
dos back util &: "\util\"
dos dir wide: "dir /W "
dos dot dot back &: "..\"
dos e colon &: "e:"
dos e colon acts &: "e:\ronny\acts\"
dos log file: "c:\acts\acts.log"
dos lpt3 &: "LPT3:"
dos temp one: "c:\dos\temp1.tmp "
zero 10 alpha: "010A"
zero eight slash 20 23: "08/2023"
zero point two five: "0.25"
zero point seven five: "0.75"
zero semi: "0;"
one zero one collins: "101 Collins Street  Melbourne"
one three cabs: "13cabs"
one m b : "1MB"
one p quote: "1(""
one point one: "1.1"
one point two hotel: "1.2h"
one point five: "1.5"
one point x: "1.x"
one sat: "1SAT"
one under: "1_"
one x: "1X"
10 71 b: "1071B"
10 charlie: "10C"
19 66: "1966"
two nine seven edgecliff: "297 Edgecliff"
two f a s : "2FAS"
two f a: "2FA"
two g five: "2g"
two g: "2G"
two gigabytes: "2GB"
two harbour: "2Harb"
two mort street: "2 Mort Street"
two s v : "2SV"
two under: "2_"
20 10: "2010"
20 11: "2011"
20 15 under zero four: "2015_04"
20 15 under zero six: "2015_06"
20 16 under zero three: "2016_03"
20 16 under 12: "2016_12"
20 17 under zero eight: "2017_08"
20 18: "2018"
20 19 under zero eight: "2019_08"
20 19: "2019"
20 20 under zero four: "2020_04"
20 20 under 11 s: "2020_11 "
20 21: "2021"
20 22 under 10: "2022_10"
20 23 under zero two: "2023_02"
20 23 under zero three: "2023_03"
20 23 under 11: "2023_11"
20 23: "2023"
20 24: "2024"
20 25: "2025"
20 27: "2027"
2008 r two: "2008R2"
2017 under zero five: "2017_05"
24 slash seven: "24/7"
25 meter: "25m"
three six five: "365"
three 90 a two: "390A2"
three 90 alpha: "390A"
three 90 delta: "390D"
three a: "3a"
three back quotes j s: "```js{End}{Enter}{Up}{BackSpace}{Down}"
three d buildings: "3D Buildings"
three g five: "3g"
three minus signs: "---"
three slash three: "3/3"
three under: "3_"
32 bit: "32-bit"
32 x 32: "32x32"
36 10: "3610"
36 20: "3620"
36 30: "3630"
36 compass drive: "36 Compass Drive"
36 hundred b e: "3600BE"
36 hundred c e: "3600CE"
36 hundred: "3600"
37 mayne: "37Mayne"
four ain tree: "4 AINTREE STREET BRUNSWICK EAST"
four bravo: "4B"
four point eight: "4.8"
four wise six: "YYYY"
four y under two m: "YYYY_MM"
41 38: "4138"
44 33: "4433"
44 64 75 75: "44647575"
five point six: "5.6"
five point seven: "5.7"
five under: "5_"
50 percent: "50%"
six under: "6_"
64 bit: "64-bit"
seven point five: "7.5"
seven under: "7_"
seven zip: "7Zip"
78 16: "7816"
eight point five: "8.5"
eight under: "8_"
nine under: "9_"
a six three six: "A636"
a a b k: "bk"
a a p t: "aapt"
a a r x: "rx"
a b a c : "ABAC"
a b d six: "ABD"
a b d: "abd"
a b l six: "ABL"
a b l: "abl"
a b n : "ABN"
a b n five: "abn"
a b n six: "ABN"
a b r v: "abrv"
a b s six: "ABS"
a b s: "abs"
a c c o r: "Accor"
a c c: "acc"
a c d c: "acdsee"
a c d see: "ACDSee"
a c els: "ACLs"
a c g : "ACG"
a c g five: "acg"
a c k: "Ack"
a c l six: "ACL"
a c m six: "ACM"
a c n : "ACN"
a c n six: "ACN"
a c n t: "acnt"
a c p i: "ACPI"
a c r six: "ACR"
a c t six: "ACT"
a c t s: "ACTS"
a c t under: "ACT_"
a c t: "act"
a d d six: "ADD"
a d d r: "addr"
a d d: "add"
a d f six: "ADF"
a d f: "adf"
a d j six: "ADJ"
a d m five: "adm"
a d m six: "ADM"
a d m: "adm"
a d n six: "ADN"
a d o six: "ADO"
a d o d b : "ADODB"
a d r s: "adrs"
a d s l six: "ADSL"
a d s l: "adsl"
a dash b: "a-b"
a deer: "Adir"
a e six: "AE"
a e under six: "AE_"
a f a i k : "AFAIK"
a f o m: "afom"
a f x message box: "AfxMessageBox("
a f x message: "AfxMessageBox("
a f x: "afx"
a g g r under: "AGGR_"
a g l six: "AGL"
a g m six: "AGM"
a g r six: "AGR"
a h six: "AH"
a h p r a: "ahpra"
a i six: "AI"
a i d six: "AID"
a i d: "aid"
a k a: "aka"
a l b six: "ALB"
a l g six: "ALG"
a l l o c: "alloc"
a l s six: "ALS"
a l t: "alt"
a m six: "AM"
a m a s six: "AMAS"
a m eyes: "AMIs"
a m i six: "AMI"
a m l six: "AML"
a m n g six: "AMNG"
a m s six: "AMS"
a m s l six: "AMSL"
a m s l: "amsl"
a n a t: "anat"
a n k i: "Anki"
a n u six: "ANU"
a n u: "Anu"
a n z six: "ANZ"
a o eyes: "AOIs"
a o i six: "AOI"
a p six: "AP"
a p a six: "APA"
a p a m d u : "APA MDU"
a p a m d u one: "ApaMdu"
a p a networks: "APA Networks"
a p a transmission: "APA Transmission"
a p a: "apa"
a p d u six: "APDU"
a p dash south east: "ap-southeast"
a p i six: "API"
a p i gateway: "API Gateway"
a p i: "api"
a p p bar one: "AppBar"
a p p dash: "app-"
a p p l: "appl"
a p p s: "apps"
a p p: "app"
a p t: "apt"
a p under: "AP_"
a q five: "aq"
a q bulk: "AqBulk"
a q m s six: "AQMS"
a q m s: "aqms"
a q p six: "AQP"
a q p under: "AQP_"
a q p: "aqp"
a q pro one: "AQPro"
a q pro five: "aqpro"
a q pro a p i: "AQ Pro API"
a q pro batch files: "D:\sw\Callpoint\AQ Pro\trunk\WebAQPro2\TestData\BatchFiles"
a q pro cust: "AQProCust"
a q pro global: "AQProGlobal"
a q pro under: "aqpro_"
a q pro: "AQ Pro"
a r c: "arc"
a r g s: "Args"
a r g v: "argv"
a r g: "arg"
a r i six: "ARI"
a r n six: "ARN"
a r n: "arn"
a s a p : "ASAP"
a s c: "asc"
a s g six: "ASG"
a s m: "asm"
a s p  dot net core: "ASP.NET Core"
a s p dot net: "ASP.NET"
a s p: "asp"
a s s o c: "assoc"
a s t six: "AST"
a s t: "ast"
a s x : "ASX"
a s x 200: "ASX 200"
a s y n c: "async"
a t 90 s: "at90s"
a t l five: "atl"
a t l: "ATL"
a t mega: "atmega"
a t n: "atn"
a t o five: "ato"
a t o six: "ATO"
a t r six: "ATR"
a t r: "atr"
a t s i c six: "ATSIC"
a t t r: "attr"
a t t: "att"
a u d: "aud"
a u g 20: "AUG20"
a u g 22 under: "AUG22_"
a u g 22: "AUG22"
a u g 23: "AUG23"
a u g: "aug"
a u s six: "AUS"
a u s post: "AusPost"
a u s t: "aust"
a u s: "aus"
a u t h: "auth"
a u t: "aut"
a v six: "AV"
a v g: "avg"
a v i one: "Avi"
a v i v i: "Avivi"
a w k: "awk"
a w s five: "aws"
a w s six: "AWS"
a w s amplify: "AWS Amplify"
a w s batch: "AWS Batch"
a w s config: "AWS Config"
a w s credentials: "AWSCredentials"
a w s e b s : "AWS EBS"
a w s e c two: "AWS EC2"
a w s e c s : "AWS ECS"
a w s e k s: "AWS EKS"
a w s edge: "AWS Edge"
a w s far gate: "AWS Fargate"
a w s fargate: "AWS Fargate"
a w s glue: "AWS Glue"
a w s i o t : "AWS IoT"
a w s i q : "AWS IQ"
a w s identity centre: "AWS Identity Centre"
a w s lambda: "AWS Lambda"
a w s local zones: "AWS Local Zones"
a w s macie: "AWS Macie"
a w s outposts: "AWS Outposts"
a w s s three: "AWS S3"
a w s shield: "AWS Shield"
a w s v p c : "AWS VPC"
a w s wavelength: "AWS Wavelength"
a w s x-ray: "AWS X-Ray"
a w s: "AWS"
a x five: "ax"
a z six: "AZ"
a z o p t: "Azopt"
a z plural: "AZs"
a zeds: "AZs"
a zees : "AZs"
access three: "Access"
acid six: "ACID"
action tech: "ActionTech"
active directory: "Active Directory"
ad hoc one: "AdHoc"
add dash: "Add-"
add in: "add-in"
address detail pid six: "ADDRESS_DETAIL_PID"
address under default geocode: "ADDRESS_DEFAULT_GEOCODE"
address under detail six: "ADDRESS_DETAIL"
address under detail pid six: "ADDRESS_DETAIL_PID"
address under feature six: "ADDRESS_FEATURE"
address under line one six: "ADDRESS_LINE1"
address under site geocode: "ADDRESS_SITE_GEOCODE"
address under site pid six: "ADDRESS_SITE_PID"
admin boundaries: "Admin Boundaries"
air b n b: "airbnb"
air rights: "Air Rights"
air tasker: "Airtasker"
alex slash r z : "Alex/RZ"
alias under principal six: "ALIAS_PRINCIPAL"
all states six: "ALLSTATES"
alpha one: "A1"
alpha two six: "A2"
alpha two: "A2"
alpha four: "A4"
alpha under: "A_"
amazon r d s : "Amazon RDS"
ampersand p under: "& p_"
ampersand p: "&p"
anaconda three: "Anaconda"
and slash or: "and/or"
andrew n g: "Andrew Ng"
angle sharp: "AngleSharp"
annex alpha: "Annex A"
annexure alpha: "Annexure A"
ant sick: "ANZSIC"
app config: "AppConfig"
app stream two point zero: "AppStream 2.0"
app sync: "AppSync"
application slash jason: "application/json"
april 20 24: "April 2024"
arc g i s : "ArcGIS"
arch e star: "Archistar"
are equal: "AreEqual"
as a service: "as a Service"
as code: "as Code"
as p e r: "as per"
ass sure a d : "Azure AD"
ass sure: "Azure"
assert dot that: "Assert.That("
assert dot throws: "Assert.Throws<>(() => "
assert x: "AssertX"
at brian: "@Brian"
at card access: "@cardaccess.com.au"
at giga: "@giga.net.au"
at odhette: "@Odhette"
at quote: "@""
at ronen: "@Ronen"
at sign left p: "@("
at star: "@*"
aug 19: "AUG19"
aug 20: "AUG20"
augmented cadlite one: "AugmentedCadLite"
augmented cadlite: "Augmented CadLite"
aus harvest: "OzHarvest"
aus post under: "auspost_"
aus post: "AusPost"
aussie center: "centre"
auth e: "Authy"
auth n z: "AuthNZ"
auth n: "AuthN"
auth z: "AuthZ"
auto complete: "autocomplete"
auto hot key: "AutoHotKey"
auto scaling: "Auto Scaling"
availability zone: "Availability Zone"
await client: "[Await Client]"
await discussion: "[Await Discussion] "
await ronny: "[Await Ronny]"
await supplier: "[Await Supplier]"
awaiting margaret: "[Awaiting Margaret]"
b two b : "B2B"
b a six: "BA"
b a l: "bal"
b a r e l: "Barel"
b a s : "BAS"
b a u d: "baud"
b b six: "BB"
b b c : "BBC"
b b colon s: "BB: "
b b discussions: "BB disc"
b b discussions: "BB discussions"
b c e : "BCE"
b cancel: "cancel"
b e l e l i: "beleli"
b e r t : "BERT"
b e r: "ber"
b f six: "BF"
b g name: "mahboos"
b g smile: ":-)"
b goto: "Goto "
b h p  coal: "BHP Coal"
b h p : "BHP"
b i five: "bi"
b i six: "BI"
b i d a l: "BiDal"
b i n: "bin"
b i t: "bit"
b j six: "BJ"
b l a h: "blah"
b l d g: "bldg"
b l d: "bld"
b l l six: "BLL"
b l l: "bll"
b l u m: "Blum"
b new: "New "
b next: "Next"
b o m: "bom"
b o t o three: "boto3"
b o x: "box"
b r i t: "brit"
b s b : "BSB"
b s p six: "BSP"
b s p: "bsp"
b s s: "bss"
b shared: "Shared "
b sub: "Sub "
b t dash: "BT-"
b t n dash: "btn-"
b t n: "btn"
b t w six: "BTW"
b u d i: "Budi"
b u f: "buf"
b u p a: "Bupa"
b u s: "bus"
b y o l : "BYOL"
back alpha: "\alpha"
back approximate: "\approx"
back back v m ware host: "\\vmware-host"
back c dot: "\cdot"
back comma: "\,"
back delta three: "\Delta"
back epsilon: "\epsilon"
back f r a c: "\frac"
back huge: "\huge"
back l t: "\lt"
back lambda: "\lambda"
back link: "backlink"
back links: "backlinks"
back not equals: "\neq"
back november: "\n"
back omega: "\omega"
back p h i: "\phi"
back pi: "\pi"
back prop to: "\propto"
back propagation: "backpropagation"
back quote november: "`n"
back quote quote: "`""
back quote romeo: "`r"
back r h o: "\rho"
back romeo: "\r"
back s u m: "\sum"
back shared folders: "\Shared Folders"
back t a u: "\tau"
back tango: "\t"
back therefore: "\therefore"
back theta one: "\theta_1"
back times: "\times"
back v e c: "\vec "
backslash n: "\n"
backup service: "Backup Service"
bam back: "Bamback"
band id: "BandId"
bank oz: "BankAus"
bar 500: "|500"
bar bar task: "||Task"
base camp: "Basecamp"
base under parcel six: "BASE_PARCEL"
bash he: "Bashi"
beagle bone: "BeagleBone"
big era waters: "Biggera Waters"
bin debug net eight windows: "bin\debug\net8.0-windows"
bin pack: "binpack"
bin yan conjugation: "BinyanConjugation"
bin yan: "binyan"
black list: "blacklist"
blacks land: "Blaxland"
blazer o: "Blazor"
block h: "Bloch"
block under street address six: "BLOCK_STREET_ADDRESS"
blue tack: "Blu-Tack"
blue tools: "BlueTools"
blue tooth: "Bluetooth"
book plural: "books"
boot strap: "bootstrap"
box one: "Box"
brat six: "BRAT"
bravo one: "B1"
bravo two: "B2"
bravo three: "B3"
bravo five: "B5"
bravo under: "B_"
brian comma ronny: "Brian, Ronny"
brian's email callpoint: "brianb@callpointspatial.com.au"
brown fields: "brownfields"
builder i d : "Builder ID"
building under address: "BUILDING_ADDRESS"
building under pid six: "BUILDING_PID"
building under: "building_"
buildings two point zero: "Buildings 2.0"
built in: "built-in"
bulk r b s : "Bulk RBS"
byte by byte: "byte-by-byte"
byte s: "BYTE "
c  handle: "HANDLE"
c three s: "CCcs"
c a b s: "CAbs"
c a d six: "CAD"
c a d under: "CAD_"
c a d: "cad"
c a f six: "CAF"
c a g r : "CAGR"
c a l c: "calc"
c a n n: "Cann"
c a n v a: "canva"
c a r t o: "carto"
c a s five: "cas"
c a t e g: "categ"
c a v v six: "CAVV"
c a z: "caz"
c b five: "cb"
c b a six: "CBA"
c b c t : "CBCT"
c b d six: "CBD"
c b d: "cbd"
c b f six: "CBF"
c b t: "cbt"
c boolean: "BOOLEAN"
c byte s: "BYTE "
c c a : "CCA"
c c c s: "CCcs"
c c colon: "CC:"
c c dc: "CDC"
c c grid one: "CGrid1"
c c o b array: "CObArray"
c c p: "CCp"
c c point: "CPoint"
c cast decimal: "(decimal)"
c caz: "CCas"
c colon back: "c:\"
c combo: "combo"
c config: "CConfig"
c cos etsi: "CCosEtsi"
c cos: "CCos"
c d k six: "CDK"
c debug: "CDebug"
c e r t: "cert"
c f five: "cf"
c f six: "CF"
c f d six: "CFD"
c f i s : "CFIS"
c f i: "cfi"
c f s six: "CFS"
c file time: "FILETIME"
c g t six: "CGT"
c h a g: "chag"
c h a i: "Chai"
c h a n i: "Chani"
c h a r s: "chars"
c h a r: "char"
c h d c six: "CHDC"
c h q: "chq"
c h r: "chr"
c h v: "chv"
c i five: "ci"
c i c d : "CI/CD"
c i d r : "CIDR"
c i d: "cid"
c i t b : "CITB"
c i t b six: "CITB"
c int array: "int[] "
c iso: "CIso"
c l six: "CL"
c l a six: "CLA"
c l a: "cla"
c l b six: "CLB"
c l b: "clb"
c l i six: "CLI"
c l i x m l: "clixml"
c l i: "cli"
c l y m: "Clym"
c m b: "cmb"
c m d: "cmd"
c m k six: "CMK"
c m p: "cmp"
c mad: "CMad"
c map e: "cMapi"
c map x: "CMapX"
c minus line: "-----------------------------------------------------------------------------"
c n c six: "CNC"
c n n six: "CNN"
c n t: "cnt"
c name of: "nameof("
c o two: "CO2"
c o five: "co"
c o a six: "COA"
c o b six: "COB"
c o c h i: "Cochi"
c o d e t: "codet"
c o h s: "COhs"
c o l s: "cols"
c o l: "col"
c o m six: "COM"
c o m b: "comb"
c o m m: "comm"
c o m: "com"
c o n d a: "conda"
c o n j: "conj"
c o n n: "conn"
c o n s: "cons"
c o n t: "cont"
c o n v: "conv"
c o n: "con"
c o o r d: "coord"
c o r p: "corp"
c o r s : "CORS"
c o s: "cos"
c o t s six: "COTS"
c p five: "cp"
c p c s: "CpCs"
c p column: "CpColumn"
c p container: "CpContainer"
c p cust dash: "cp-cust-"
c p dash aurora: "cp-aurora"
c p data: "CpData"
c p dataset repo: "cp-dataset-repo"
c p decimal: "CpDecimal"
c p exception: "CpException"
c p f d r: "CpFdr"
c p i : "CPI"
c p i six: "CPI"
c p info sec: "CP_INFOSEC"
c p line segment: "CpLineSegment"
c p line: "CpLine"
c p logger: "CpLogger"
c p message box: "CpMessageBox"
c p multi polygon: "CpMultipolygon"
c p point: "CpPoint"
c p polygon: "CpPolygon"
c p qualify: "CpQualify"
c p rectangle: "CpRectangle"
c p ring: "CpRing"
c p rom: "cp_rom"
c p s dash nas: "CPS-NAS"
c p s q l: "CpSql"
c p s v n: "CpSvn"
c p t six: "CPT"
c p t: "cpt"
c p table type: "CpTableType"
c p table u r l: "CpTableUrl"
c p table: "CpTable"
c p under: "cp_"
c p y: "cpy"
c percent delta: "%d"
c point: "CPoint"
c r three: "Cr"
c r n t: "crnt"
c r o n: "cron"
c r p six: "CRP"
c r s six: "CRS"
c s five: "cs"
c s a: "csa"
c s b six: "CSB"
c s g : "CSG"
c s p: "csp"
c s r six: "CSR"
c s s six: "CSS"
c s s: "css"
c s v: "csv"
c sharp three: "CSharp"
c sharp eight: "C# 8"
c sharp: "C#"
c string one: "CString1"
c string s: "CString "
c system time: "SYSTEMTIME"
c t six: "CT"
c t a p six: "CTAP"
c t l v: "CTlv"
c t r l: "ctrl"
c t scan: "CT Scan"
c t x: "ctx"
c time span: "CTimeSpan"
c to do: "// TODO: "
c u f a r: "Cufar"
c u in pointer: "UIntPtr"
c u r l: "curl"
c u s t under: "cust_"
c u s t: "cust"
c u sim: "CUsim"
c uick: "CUicc"
c v five: "cv"
c v s e com: "C:\sw\cas\cvsmnt\ecom\"
c v v six: "CVV"
c v v: "cvv"
c variant: "VARIANT"
c y b g six: "CYBG"
cad parcel id six: "CAD_PARCEL_ID"
cad states: "CAD States"
cad under six: "CAD_"
cad under pid six: "CAD_PID"
cad under polygon p i d: "CAD_POLYGON_PID"
cadastre under pid six: "CADASTRE_PID"
cadlite extra: "Cadlite Extra"
cal three d: "Cal3D"
call point: "Callpoint"
callpoint s v n: "D:\sw\Callpoint\"
callpoint spatial: "Callpoint Spatial"
can six: "CAN"
cancelled colon s: "Cancelled: "
cap sierra two: "S2"
cap sierra three: "S3"
cap sierra four: "S4"
cap sierra seven: "S7"
cap tea: "Capti"
cap x: "CapEx"
capitalize next two: "CapitalizeNext 2"
caps r two: "R2"
caps v one v two: "V1 V2"
caps v one: "V1"
capture under date six: "CAPTURE_DATE"
card list type: "CardListType"
card pro: "CardPro"
cas pad six: "CASPAD"
case else: "Case Else"
case law: "Caselaw"
cast double: "(double)"
cast float: "(float)"
cast l p c t: "(LPCTSTR)"
cast l p c: "(LPCSTR)"
cast p s custom object: "[pscustomobject]"
caz l i b: "caslib"
center aus: "centre"
center link: "Centrelink"
centroid edition: "Centroid Edition"
change log dot m d: "changelog.md"
change log: "changelog"
charlie three: "C3"
chat g p t : "ChatGPT"
check box one: "CheckBox"
cheque q: "cheque"
child item : "ChildItem "
chile olives: "ChilliOlives"
chrome one: "Chrome"
click send: "ClickSend"
close z: "cloze"
closure z: "clozure"
closures z: "clozures"
cloud berry: "CloudBerry"
cloud formation: "CloudFormation"
cloud front: "CloudFront"
cloud h s m : "CloudHSM"
cloud shell: "CloudShell"
cloud trail: "CloudTrail"
cloud watch: "CloudWatch"
co pilot one: "Copilot"
co point: "CoPoint"
coalesce left: "COALESCE("
coat six: "COAT"
code artifact: "CodeArtifact"
code build: "CodeBuild"
code commit: "CodeCommit"
code deploy: "CodeDeploy"
code pipeline: "CodePipeline"
code star: "CodeStar"
codet three: "Codet"
codet six: "CODET"
cog paf six: "COGPAF"
cognito one: "Cognito"
colon colon colon: ":::"
colon n zero: ":N0"
colon number: ": number"
colon slash slash: "://"
colon string: ": string"
colon void: ": void"
color u: "colour"
colour o: "color"
com bank: "CommBank"
combo box: "ComboBox"
comma zero right p: ", 0)"
comma m under: ", m_"
comma ronny: ", Ronny"
command let: "cmdlet"
commander one: "Commander"
compare dash: "Compare-"
comprehend one: "Comprehend"
computer share: "Computershare"
con cat left: "concat("
con cat: "concat"
connect one: "Connect"
connect os: "connectOS"
copy dash: "Copy-"
corner under flag equals y: "CORNER_FLAG = 'Y'"
cosmos d b : "CosmosDB"
covid dash 19: "COVID-19"
cry engine: "CRYENGINE"
cull de sack: "cul-de-sac"
curb or us: "Kerberos"
cust p b dep: "CustPbdep"
cyber bank: "Cyberbank"
d one under: "D1_"
d two under: "D2_"
d three under: "D3_"
d a five: "da"
d a six: "DA"
d a c: "dac"
d a g six: "DAG"
d a i d: "DAId"
d a l: "dal"
d a p six: "DAP"
d a r six: "DAR"
d a t: "dat"
d a under: "DA_"
d a x six: "DAX"
d b five: "db"
d b a: "dba"
d b data: "DbData"
d b dot t three medium: "db.t3.medium"
d b dot t three small: "db.t3.small"
d b g error: "DBG_ERROR"
d b g event: "DBG_EVENT"
d b g exit error: "DBG_EXIT_ERROR"
d b g exit: "DBG_EXIT"
d b g function: "DBG_FUNCTION(""
d b g note: "DBG_NOTE"
d b g thread: "DBG_THREAD(""
d b g trace: "DBG_TRACE"
d b o five: "dbo"
d b o: "dbo"
d b parameter: "DbParameter"
d b r: "dbr"
d b s: "dbs"
d b under all: "DB_ALL"
d c a six: "DCA"
d c d six: "DCD"
d c d: "dcd"
d d six: "DD"
d d e: "dde"
d d fix: "DdFix"
d d k: "DDK"
d d o s : "DDoS"
d d p six: "DDP"
d d r dash: "DDR-"
d d r under: "DDR_"
d d r: "ddr"
d e c 22: "DEC22"
d e c six: "DEC"
d e c: "dec"
d e f n: "defn"
d e f s: "defs"
d e f: "def"
d e j a i: "dejai"
d e l i m: "delim"
d e l: "del"
d e m six: "DEM"
d e m: "dem"
d e p: "dep"
d e r six: "DER"
d e s c: "Desc"
d e s t: "dest"
d e v: "dev"
d e x a : "DEXA"
d e x a six: "DEXA"
d f five: "df"
d f six: "DF"
d f c e six: "DFCE"
d f e i t: "dfeit"
d f t: "dft"
d g tech: "DGtek"
d g v: "dgv"
d h c p six: "DHCP"
d h l six: "DHL"
d h t m l : "DHTML"
d i b: "DIB"
d i c t: "dict"
d i d six: "DID"
d i dees : "DIDs"
d i f f: "diff"
d i j k: "dijk"
d i m a: "Dima"
d i r s: "dirs"
d i r: "dir"
d i s p: "disp"
d i s t: "dist"
d i v: "div"
d k i m six: "DKIM"
d l elves : "DLLs"
d l g: "dlg"
d l l six: "DLL"
d l l: "dll"
d l p six: "DLP"
d link: "D-Link"
d m s six: "DMS"
d n seven l i b: "Dn7Lib"
d n l i b: "DnLib"
d n s six: "DNS"
d n s: "dns"
d o five: "do"
d o b six: "DOB"
d o c s: "docs"
d o c: "doc"
d o d: "dod"
d o f six: "DOF"
d o m: "dom"
d o n t: "dont"
d o t net core: "Dot.NET Core"
d o t net framework: "Dot.NET Framework"
d o t net: "Dot.NET"
d p i d six: "DPID"
d p i d: "dpid"
d p i: "dpi"
d q n six: "DQN"
d r five: "dr"
d r six: "DR"
d r e m e l: "dremel"
d r o r: "Dror"
d r p : "DRP"
d r p six: "DRP"
d r s six: "DRS"
d s l six: "DSL"
d s l a m: "dslam"
d s m six: "DSM"
d tack dash 100: "DTAC-100"
d to p: "DToP"
d u b: "dub"
d u e: "due"
d u i: "dui"
d v d five: "dvd"
d word s: "DWORD "
darrell one l: "Darrel"
dash 20 18: "-2018"
dash 20 21: "-2021"
dash a p i : "-API"
dash claire to ronny: "- Claire to Ronny -"
dash force: " -Force "
dash i d five: "-id"
dash not s: "-not "
dash r z: "-rz"
dash ronny to claire: "- Ronny to Claire -"
dash ronny to yael: "- Ronny to Yael -"
dash x x: "-xx"
dash yael to ronny: "- Yael to Ronny -"
data  dist: "DataDist"
data frame: "DataFrame"
data grid view: "DataGridView"
data grid: "DataGrid"
data jet: "Datajet"
data license: "DataLicense"
data lists: "Datalists"
data row: "DataRow"
data set three: "DataSet"
data set edition: "DatasetEdition"
data set id: "DatasetId"
data set: "dataset"
data sets: "datasets"
data store: "DataStore"
data sync: "DataSync"
data table: "DataTable"
data view: "dataview"
dataset a p i one: "DatasetApi"
datasets a p i one: "DatasetsApi"
date time: "DateTime"
date under created six: "DATE_CREATED"
date under modified six: "DATE_MODIFIED"
dav ron: "DavRon"
david jensen: "David Jensen"
david jensonberg: "davidjensonberg"
day or night: "DayOrNight"
de whyn: "De-Whyn"
dear code commit: "d:\CodeCommit"
dear git hub o s r : "D:\github\osr"
dear o s r: "d:\github\osr\"
dear obsidian my stuff: "d:\obsidian\obsidian\MyStuff\"
dear obsidian people: "d:\obsidian\obsidian\people\"
dear obsidian: "d:\obsidian\obsidian\"
dear organizations: "d:\obsidian\obsidian\organisations"
dear tax receipts: "e:\documents\finance\tax\2024\receipts"
december 20 22: "December 2022"
deck tree: "deckTree"
deep fake: "deepfake"
deep racer: "DeepRacer"
delete dash: "Delete-"
delta temp back: "d:\temp\"
demo one: "demo1"
desk one: "DESK1"
desk two: "DESK2"
desk five: "DESK5"
dest d l l lib: "DESTDLLLib"
detective one: "Detective"
dev art: "Devart"
dev ops: "DevOps"
dev under data: "DEV_DATA"
device i  o  control: "DeviceIoControl"
dialog result: "DialogResult"
dictionary left: "Dictionary<"
dir medical reports: "d:\obsidian\medical\reports"
direct connect: "Direct Connect"
directory  point cook: "E:\Documents\Callpoint\Customers\Ericsson\Stage 1\PointCook"
directory echo temp: "e:\temp"
directory f d r: "E:\FDR"
directory obsidian organisations: "d:\obsidian\obsidian\organisations"
directory papa temp back: "P:\temp\"
directory software logs: "c:\sw\logs"
directory tax receipts: "e:\documents\finance\tax\2023\receipts"
directory temp logs: "c:\temp\logs"
directory temp: "c:\temp"
do modal: "DoModal()"
doc you sign: "DocuSign"
doctor forner: "Dr Forner"
doctor giri: "Dr Giri"
doctor levin: "Dr Levin"
doctor mundell: "Dr Mundell"
doctor o o i: "Dr Ooi"
doctor shill off: "Dr Chilov"
doctor spar: "Dr Spahr"
doctor we: "Dr Ooi"
doctor wettstein: "Dr Wettstein"
documents amatek: "D:\Documents\Amatek"
documents callpoint: "C:\Users\ronny\Documents\CallPoint"
documents codet: "D:\Documents\Amatek\Codet"
documents organizations: "C:\Users\ronny\Documents\Organisations"
dollar at quote: "$@""
dollar dollar large: "$\large ${Left}"
dollar dollar right arrow: "$\rightarrow$"
dollar l alpha: "$a"
dollar l file one: "$file1"
dollar left: "$("
dollar quote: "$""
dollar s t r: "$str"
dollar sign dollar: "$$"
dollar true: "$True"
domain one: "Domain"
door dash: "DoorDash"
dos c d: "cd "
dos key: "doskey"
dot  one dot  one: ".1.1"
dot  begin: ".begin()"
dot  data: ".data()"
dot  dot  slash: "../"
dot  first: ".first"
dot  format t: ".Format(_T(""
dot  format: ".Format("
dot  is: ".Is"
dot  second: ".second"
dot  v t: ".vt"
dot add: ".Add"
dot any: ".Any("
dot append: ".Append"
dot are equal: ".AreEqual("
dot are: ".Are"
dot c p six: ".CP"
dot c s t r: ".c_str()"
dot checked: ".Checked"
dot clear: ".Clear"
dot close: ".Close"
dot columns: ".Columns"
dot count: ".Count"
dot d o: ".Do("
dot debug: ".Debug("
dot e b extensions: ".ebextensions"
dot equals to: ".EqualsTo("
dot equals: ".Equals("
dot error: ".Error("
dot get value: ".GetValue("
dot has value: ".HasValue"
dot has: ".Has"
dot height: ".Height"
dot index: ".Index"
dot info format: ".InfoFormat("
dot info: ".Info("
dot instance: ".Instance"
dot items: ".Items"
dot key: ".Key"
dot keys: ".Keys"
dot left: ".Left"
dot length: ".length"
dot list: ".List"
dot log line: ".LogLine("
dot log: ".Log"
dot m under: ".m_"
dot message: ".Message"
dot n e t 66: ".NET 6"
dot name: ".Name"
dot net four point eight: ".NET4.8"
dot net seven: ".NET 7"
dot net core: ".NET Core"
dot net framework: ".NET Framework"
dot net lambda: "dotnet Lambda"
dot net standard: ".NET Standard"
dot new line: ".NewLine"
dot non: ".Non"
dot now: ".Now"
dot open: ".Open("
dot read: ".Read"
dot root: ".Root"
dot set: ".Set"
dot show: ".Show("
dot string: ".String"
dot style: ".Style"
dot t p g : ".TPG"
dot t x t space: ".txt "
dot tables: ".Tables"
dot text: ".Text"
dot throws lambda: ".Throws(() => "
dot to array: ".ToArray"
dot to list: ".ToList"
dot to string: ".ToString()"
dot to: ".To"
dot total: ".Total"
dot try: ".Try"
dot type: ".Type"
dot value of: ".valueOf("
dot value: ".Value"
dot visible: ".Visible"
dot width: ".Width"
dot write line: ".WriteLine("
dot write: ".Write"
dot y: ".Y"
dr gator: "Dr Jager"
drop down one: "DropDown"
dub cast string: "[string]"
dub catch: "Catch"
dub else: "Else"
dub false: "$false"
dub get help: "Get-Help "
dub get: "Get-"
dub host: "Host "
dub if: "If ("
dub mandatory equals true: "Mandatory = $True"
dub measure: "Measure-"
dub null: "$null"
dub prams left: "Params("
dub test path: "Test-Path "
dub true: "$true"
dub type string: "[String]"
dub while: "While ("
due date: "DueDate"
due to: "due to"
dynamo d b: "DynamoDB"
e b six: "EB"
e b s six: "EBS"
e b s dash backed: "EBS-backed"
e b under six: "EB_"
e bay: "ebay"
e book: "ebook"
e c two six: "EC2"
e c two volume: "EC2Volume"
e c two: "EC2"
e c six: "EC"
e c a j : "ECAJ"
e c g one: "ECG-1"
e c g four: "ECG-4"
e c g six: "ECG"
e c g seven: "ECG-7"
e c g nine: "ECG-9"
e c g util: "EcgUtil"
e c g: "ecg"
e c r six: "ECR"
e c s six: "ECS"
e com com: "EComCOM"
e com: "ECom"
e connect plus: "eConnectPlus"
e d t: "edt"
e d v : "EDV"
e d v six: "EDV"
e e five: "ee"
e e six: "EE"
e e a s: "eeas"
e e r: "eer"
e e route one: "EeRoute"
e e route: "EE Route"
e e under: "EE_"
e e white list: "EE Whitelist"
e e zoning one: "EeZoning"
e e zoning: "EE Zoning"
e eye: "eye"
e f five: "ef"
e f a r r: "EfArr"
e f a s: "efas"
e f d i r: "EfDir"
e f d: "efd"
e f p b r: "EfPbr"
e f s six: "EFS"
e f t : "EFT"
e fail: "E_FAIL"
e g g: "egg"
e k g six: "EKG"
e k s six: "EKS"
e l five: "el"
e l b six: "ELB"
e l e y: "Eley"
e l i e: "Elie"
e l i: "Eli"
e l p i six: "ELPI"
e m c six: "EMC"
e m o j i: "emoji"
e m r six: "EMR"
e m r dash: "emr-"
e m r f s : "EMRFS"
e m r: "emr"
e n t six: "ENT"
e n t s: "ents"
e n t: "ent"
e n u m: "enum"
e n v: "env"
e o f six: "EOF"
e o f: "eof"
e o l six: "EOL"
e p l b : "EPLB"
e p l b six: "EPLB"
e p l bees: "EPLBs"
e p s g : "epsg"
e p s g six: "EPSG"
e q five: "eq"
e q: "eq"
e r c p : "ERCP"
e r c p six: "ERCP"
e r e v: "erev"
e r f s: "erfs"
e r r s t r: "ErrStr"
e r r: "err"
e s a six: "ESA"
e s a: "esa"
e s g : "ESG"
e s p 32: "ESP32"
e s r i : "ESRI"
e s r i five: "esri"
e s r i: "esri"
e t a six: "ETA"
e t effs: "ETFs"
e t f six: "ETF"
e t l six: "ETL"
e t s i six: "ETSI"
e t s i: "etsi"
e t u: "etu"
e under a p a: "E_APA"
e v five: "ev"
e v six: "EV"
e v a l: "eval"
e v c three: "evc3"
e v c: "evc"
e v t: "evt"
e w k b six: "EWKB"
e x five: "ex"
e x c: "exc"
e x e c: "exec"
e x e r six: "EXER"
e x e: "exe"
e x p r: "expr"
e x p: "exp"
e x t: "ext"
e y e: "eye"
e y l o n: "Eylon"
e z six: "EZ"
ear buds: "earbuds"
earth sized: "earth-sized"
easy card: "EasyCard"
echo colon back: "e:\"
edge cliff: "Edgecliff"
elana zulaikha: "Elana Zulaikha"
elastic cache: "Elasticache"
elastic search: "Elasticsearch"
em goo: "emgu"
email rob mar: "robmar@hear-here.com.au"
end dash user: "end-user"
end function: "End Function"
end point: "endpoint"
end select: "End Select"
end using: "End Using"
end while: "WEnd"
energy australia: "EnergyAustralia"
enterprise ethernet: "Enterprise Ethernet"
equals column left p: "=COLUMN("
equals equals: "=="
equals s: "= "
equals sign at: "=@"
equals victor: "=V"
err m s g: "ErrMsg"
err s t r: "ErrStr"
esa under code six: "ESA_CODE"
essential one: "Essential"
event a r g s: "EventArgs"
event bridge: "EventBridge"
event bus: "EventBus"
ex cali draw: "Excalidraw"
excerpt from s: "excerpt from{Space}"
exchange info: "ExchangeInfo"
exit function: "Exit Function"
exit sub: "Exit Sub"
expected r f s : "Expected RFS"
export dash: "Export-"
f a a s: "FaaS"
f a q: "FAQ"
f a r six: "FAR"
f arrow: "-}"
f c p six: "FCP"
f c p: "fcp"
f c s six: "FCS"
f d six: "FD"
f d c a six: "FDCA"
f d r six: "FDR"
f d r under: "FDR_"
f d s six: "FDS"
f d s: "fds"
f e five: "fe"
f e b 21: "FEB21"
f e b 22: "FEB22"
f e b 23: "FEB23"
f e b: "feb"
f e p six: "FEP"
f i f o six: "FIFO"
f i f o: "fifo"
f i l: "fil"
f l i r: "flir"
f l u: "flu"
f level: "fevel"
f m five: "fm"
f m six: "FM"
f m e six: "FME"
f m o six: "FMO"
f m o d: "fmod"
f n five: "fn"
f n a six: "FNA"
f n n six: "FNN"
f o f i: "fofi"
f o i six: "FOI"
f o i: "foi"
f o r e: "fore"
f o r: "for"
f p five: "fp"
f p l: "fpl"
f q d n six: "FQDN"
f r e q: "freq"
f r m: "frm"
f s five: "fs"
f s a six: "FSA"
f s a designation: "FSA Designation"
f s a m six: "FSAM"
f s a m: "fsam"
f s a: "fsa"
f s r s six: "FSRS"
f s x : "FSx"
f sam six: "FSAM"
f sams: "FSAMs"
f sound under: "FSOUND_"
f t p s : "FTPS"
f t p: "ftp"
f t t b: "fttb"
f t t c six: "FTTC"
f t t n six: "FTTN"
f t t n: "fttn"
f t t p six: "FTTP"
f t t p: "fttp"
f t t x: "fttx"
f u n c: "func"
f y 18: "FY18"
f y 19: "FY19"
f y 20 23: "FY2023"
f y 22: "FY22"
f y 23: "FY23"
f y 24: "FY24"
f y 25: "FY25"
f y i at brian: "FYI @Brian"
fabula tech: "FabulaTech"
fail over: "failover"
failed result: "FAILED(Result)"
falcon nine: "FALCON9"
far gate: "Fargate"
far hood: "Farhud"
fat 32: "FAT32"
feature u r l: "FeatureUrl"
feb 19: "FEB19"
feb 20 ronny annexure: "FEB20_RONNY_ANNEXURE"
feb 20: "FEB20"
feb dash 20 20: "feb-2020"
february 20 22: "February 2022"
feed forward: "feedforward"
fibre asset: "fibre asset"
fibre con x: "FibreconX"
fibre expansion program one: "FibreExpansionProgram"
fibre expansion program: "Fibre Expansion Program"
fibre on net: "fibre On-Net"
fibre pit one: "FibrePit"
fibre pit three: "Fibre Pit"
fibre vision: "Fibervision"
file info: "FileInfo"
file set: "FileSet"
file time: "FILETIME"
file zilla: "FileZilla"
filename i d: "FilenameId"
fill dash in: "fill-in"
fill under in six: "FILL_IN"
fire fox: "firefox"
first f: "first"
five err: "fiverr"
flat slash level: "flat/level"
flat under number six: "FLAT_NUMBER"
flavor u: "flavour"
flow chart: "flowchart"
fly buys: "flybuys"
folder enter: "folder"
form bay: "Formbay"
format dash: "Format-"
format left p: "FORMAT("
fort e gate: "FortiGate"
fortnight e: "fortnite"
fox tell: "Foxtel"
foxtrot under: "F_"
free call: "freecall"
freeable memory: "Freeable Memory"
frog e: "froggy"
from b b colon: "From BB:"
from b b: "From BB"
from colon alex: "From: Alex{Enter}"
from colon brian: "From: Brian{Enter}"
from colon claire: "From: Claire{Enter}"
from colon margaret: "From: Margaret"
from colon: "From:"
front end: "front-end"
front matter: "frontmatter"
fy dough six: "FIDO"
g a six: "GA"
g a d: "gad"
g a dem: "GA DEM"
g a discussions: "GA disc"
g a l i a: "Galia"
g a l i t: "Galit"
g a l i: "Gali"
g and d: "G&D"
g b six: "GB"
g b l: "gbl"
g b: "gb"
g c five: "gc"
g c c s a: "gccsa"
g d a 19 94: "GDA1994"
g d a 20 20: "GDA2020"
g d a 94: "GDA94"
g d a l six: "GDAL"
g d a l: "gdal"
g d b six: "GDB"
g d b: "gdb"
g d i five: "gdi"
g d p r : "GDPR"
g dal six: "GDAL"
g dal info three: "GdalInfo"
g dal slash o g r : "GDAL/OGR"
g dal warp: "GdalWarp"
g dash n a f: "G-NAF"
g dash naf: "G-NAF"
g e d two: "ged2"
g e d cadastre info: "GedCadastreInfo"
g e d: "ged"
g e n: "gen"
g e o c: "geoc"
g e o datum: "GeoDatum"
g e o m: "geom"
g e o: "geo"
g f c: "gfc"
g g six: "GG"
g g a six: "GGA"
g g m six: "GGM"
g g o x six: "GGOX"
g g t six: "GGT"
g g under v : "GG_V"
g g under: "GG_"
g h d six: "GHD"
g h g six: "GHG"
g i five: "gi"
g i six: "GI"
g i o : "GIO"
g i r i: "Giri"
g i s : "gis"
g i s five: "gis"
g i s six: "GIS"
g i s assets: "GIS Assets"
g i s boundaries: "GIS Boundaries"
g i s t a : "GISTA"
g i t: "git"
g j x : "GJX"
g j x under: "GJX_"
g k strata: "GK Strata"
g mail: "gmail"
g n a f six: "GNAF"
g n a f: "gnaf"
g naf six: "GNAF"
g naf augmented: "G-NAF Augmented"
g naf core: "G-NAF Core"
g naf extended data: "GnafExtendedData"
g naf geocode mean : "GNAF_GEOCODE_MEAN"
g naf geocoder: "GNAF Geocoder"
g naf no nap: "GnafNoNap"
g naf slash x f l : "GNAF/XFL"
g naf under pid: "GNAF_PID"
g naf under: "GNAF_"
g naf under: "GNAF_"
g o t o: "goto"
g o x six: "GOX"
g p two five: "gp2"
g p three five: "gp3"
g p six: "GP"
g p s : "GPS"
g p s five: "gps"
g p s tools net: "GpsToolsNET"
g p t : "GPT"
g p t three: "GPT-3"
g p t six: "GPT"
g p u : "GPU"
g r c six: "GRC"
g r d six: "GRD"
g r d: "grd"
g r e p: "grep"
g r p c : "gRPC"
g r p: "grp"
g r u six: "GRU"
g s six: "GS"
g s admin bounds: "GSAdmin Bounds"
g s eyes : "GSIs"
g s i six: "GSI"
g s m five: "gsm"
g s property: "GSProperty"
g s roads: "GSRoads"
g s s u six: "GSSU"
g s s u: "gssu"
g s t: "GST"
g t e: "gte"
g t r six: "GTR"
g u i five: "gui"
g u i six: "GUI"
g u i d six: "GUID"
g u i: "gui"
g under g s : "G_GS"
g v x: "gvx"
g w l b six: "GWLB"
g w l: "gwl"
gant t: "Gantt"
gap geocode three: "Gap Geocode"
gary at hot mail: "gazzaturner@hotmail.com"
gem plus: "GemPlus"
gen one: "Gen 1"
gen two: "Gen 2"
gen three: "Gen 3"
geo database: "geodatabase"
geo jason: "GeoJSON"
geo scape: "Geoscape"
geo sciences: "Geosciences"
geo tiff six: "GEOTIFF"
geo vision: "Geovision"
geoc address detail: "GeocoderAddressDetail"
geocode under type code six: "GEOCODE_TYPE_CODE"
geocoded paf: "Geocoded PAF"
geocoder options one: "GeocoderOptions"
geocoder result two: "GeocoderResult2"
geok support: "Geoc support"
geoscape two point zero: "Geoscape 2.0"
geoscape extra: "Geoscape Extra"
geoscape oz: "GeoscapeAU"
geoscape under: "GEOSCAPE_"
gis ta: "GISTA"
git hub: "GitHub"
git lens: "GitLens"
global sat: "GlobalSat"
gnaf under pid: "GNAF_PID"
go daddy: "GoDaddy"
grammar cardinality: "GrammarCardinality"
grammar gender: "GrammarGender"
grammar person: "GrammarPerson"
grammar tense: "GrammarTense"
grand stream: "Grandstream"
graph q l : "GraphQL"
graph x: "GraphX"
green space: "greenspace"
grid view: "GridView"
ground truth: "Ground Truth"
group under six: "GROUP_"
guard duty: "GuardDuty"
guard time: "guardtime"
gum tree: "Gumtree"
h a three: "Ha"
h a m a s: "Hamas"
h a t: "hat"
h a x m : "HAXM"
h break: "<br/>"
h c f : "HCF"
h c f six: "HCF"
h c t: "HCT"
h d d six: "HDD"
h d f s six: "HDFS"
h d m i : "HDMI"
h e c six: "HEC"
h e x: "hex"
h e y: "hey"
h f c six: "HFC"
h f c: "hfc"
h f l one six: "HFL1"
h f l six: "HFL"
h f l delta: "HFL Delta"
h f l p f l : "HFL/PFL"
h f l p f l three: "HflPfl"
h f l: "hfl"
h g o x six: "HGOX"
h g r: "hgr"
h g under six: "HG_"
h h five: "hh"
h h annotated: "HhAnnotated"
h h audio: "HhAudio"
h h c s: "HhCs"
h h code: "HhCode"
h h debug: "HhDebug"
h h earth: "HhEarth"
h h g p s: "HhGps"
h h geometry: "HhGeometry"
h h logger: "HhLogger"
h h m: "hhm"
h h maps: "HhMaps"
h h message box: "HhMsgBox"
h h p: "hhp"
h h player: "HhPlayer"
h h point: "HhPoint"
h h postcode: "2010"
h h recorder: "HhRecorder"
h h rectangle: "HhRectangle"
h h simulator: "HhSimulator"
h h studio: "HhStudio"
h h t t: "hhtt"
h h t: "hht"
h h trip: "HhTrip"
h h watchdog: "HhWatchdog"
h i n six: "HIN"
h i s t: "hist"
h key: "HKEY"
h line break: "<br/>"
h m d six: "HMD"
h mod: "hmod"
h nikud: "nikud"
h o u z z: "houzz"
h p c six: "HPC"
h p s six: "HPS"
h paragraph open: "<p>"
h paragraph: "<p>"
h r e f: "href"
h r r l six: "HRRL"
h r r l m r p : "HRRL/MRP"
h r r l: "hrrl"
h result s: "HRESULT "
h result: "HRESULT"
h s l six: "HSL"
h t m l six: "HTML"
h t m l element: "HTMLElement"
h t m l: "html"
h t t p six: "HTTP"
h t t p s six: "HTTPS"
h t t p s: "https"
h t t p: "http"
h t w six: "HTW"
h triple c: "HCCC"
h w l six: "HWL"
h w l e : "HWLE"
h w n d six: "HWND"
h x five: "hx"
ha bud: "Chabad"
hands free: "handsfree"
harabeleben: "Shit in your yogurt"
harbour quays: "Harbour Quays"
hark ham: "Harkham"
has under geometry: "HAS_GEOMETRY"
has under residential: "HAS_RESIDENTIAL"
hash 58: "#58"
hash cards m l: "#flashcards/ml"
hash if define win 32: "#ifdef WIN32"
hash if not defined: "#ifndef "
hash import: "#import ""
hash person slash: "#person/"
hash pragma: "#pragma "
hash review: "#review"
hash set left: "HashSet<"
hash set: "HashSet"
hash table: "Hashtable"
hash undefine: "#undef "
hat two: "^2"
hat 99: "^99"
hat slash: "^/"
hat x-ray: "^x"
head six: "HEAD"
hear here one: "HearHere"
hear here a b n: "86 113 905 570"
hear here a c n: "113 905 570"
hear here r z: "hearhererz"
hear hyphen here: "hear-here"
hebrew bread: "challah"
hebrew complete healing: "Refuah Shlemah"
hebrew dash: "hebrew-"
hebrew happy new year: "Shana Tova"
hebrew phrase: "HebrewPhrase"
hebrew source: "HebrewSource"
hebrew word one: "HebrewWord"
hi ashlesha: "Hi Ashlesha"
hi ha: "Hi Ha"
hi jenny: "Hi Jenny"
hi no g: "Hi"
high pages: "hipages"
high tail one: "Hightail"
high tail: "hightail"
hire h: "Haier"
home track: "Hometrack"
host gator: "HostGator"
hot dock: "HotDoc"
hot mail: "hotmail"
hotel three: "H3"
hybrid geocoder: "Hybrid Geocoder"
hyper v: "Hyper-V"
i one six seven: "i167"
i one 80: "i180"
i pod: "iPod"
i prime us: "iPrimus"
i  b  a  p: "ibap"
i a six: "IA"
i a a s: "IaaS"
i a c: "IaC"
i a m six: "IAM"
i a t a : "IATA"
i c r six: "ICR"
i c r: "icr"
i c s m : "ICSM"
i cloud: "iCloud"
i d five: "id"
i d six: "ID"
i d d six: "IDD"
i d d: "idd"
i d descending: "ID DESC"
i d e n t: "ident"
i d equals five: "id="
i d f six: "IDF"
i d o k: "IDOK"
i d s six: "IDS"
i d x: "idx"
i dash med: "I-Med"
i data: "iData"
i disposable: "IDisposable"
i e seven: "IE7"
i enumerable left: "IEnumerable<"
i enumerable: "IEnumerable"
i equitable: "IEquatable"
i f triple t : "IFTTT"
i g five: "ig"
i g i s: "IGis"
i g w six: "IGW"
i go: "iGO"
i h h: "IHh"
i herb: "iHerb"
i i c six: "IIC"
i i f: "iif"
i i s : "IIS"
i i s six: "IIS"
i l d a s m: "ildasm"
i l r six: "ILR"
i l r review: "[ILR Review]"
i m g: "img"
i m h o six: "IMHO"
i m o six: "IMO"
i m p l: "impl"
i m u six: "IMU"
i m u t: "imut"
i med: "I-MED"
i n c i t s: "incits"
i n c: "inc"
i n f o: "info"
i n f: "inf"
i n g six: "ING"
i n g: "ing"
i n i t: "init"
i n m: "inm"
i n s five: "ins"
i n s six: "INS"
i n s t: "inst"
i n s: "ins"
i n t l: "intl"
i n t p t r: "IntPtr"
i n t point: "IntPoint"
i n t: "int"
i o one: "io1"
i o two: "io2"
i o five: "io"
i o c t elves: "IOCTLs"
i o c: "IoC"
i o p s : "IOPS"
i o t three: "IoT"
i o t core: "IoT Core"
i o t green grass: "IoT Greengrass"
i o1 five: "io1"
i p five: "ip"
i p c c : "IPCC"
i p v four: "IPv4"
i p v six: "IPv6"
i pack: "iPaq"
i pad: "iPad"
i q r six: "IQR"
i r discussions: "IR disc"
i r l : "IRL"
i r p: "irp"
i r peas: "IRPs"
i s o six: "ISO"
i s o: "iso"
i s r six: "ISR"
i s r s: "ISrs"
i s r: "isr"
i saver: "iSaver"
i t six: "IT"
i t i l six: "ITIL"
i t r o : "ITRO"
i t r o six: "ITRO"
i tunes: "iTunes"
i unknown: "IUnknown"
i v l: "ivl"
i v r : "IVR"
i w i w d : "IWIWD"
i w m six: "IWM"
id consulting: "id Consulting"
import dash module: "Import-Module"
import dash: "Import-"
in box: "inbox"
in car: "in-car"
in progress: "In Progress"
include back: "include\"
info sec: "InfoSec"
initialize dash: "Initialize-"
ink scape: "Inkscape"
insta gram: "Instagram"
install dash: "Install-"
instance id one: "InstanceId"
inter mod: "Intermod"
intruder one: "Intruder"
is dot equal to: "Is.EqualTo("
is null left p: "IsNull("
item property: "ItemProperty"
j a b r a: "jabra"
j a n: "jan"
j a s : "Jas"
j b d : "JBD"
j c a : "JCA"
j c a six: "JCA"
j e s t: "Jest"
j g six: "JG"
j i b i n: "Jibin"
j i t: "jit"
j j six: "JJ"
j l l six: "JLL"
j n f : "JNF"
j o n o: "Jono"
j p e g: "jpeg"
j q l: "jql"
j s five: "js"
j s o n: "json"
j t t six: "JTT"
j t t: "jtt"
j u l a i: "Julai"
j u l: "jul"
j u n 22: "JUN22"
j u n 23: "JUN23"
j u n: "jun"
j v six: "JV"
j w t : "JWT"
j w t six: "JWT"
jack green: "Jackgreen"
january 20 19: "January 2019"
january 20 23: "January 2023"
jason six: "JSON"
java s: "java "
java script five: "javascript"
java script: "JavaScript"
jazz three: "Jas"
jeera six: "JIRA"
jet star: "Jetstar"
jim kirk: "Jim Kirk"
jira five: "jira"
join dash: "Join-"
juggle no e: "Juggl"
july 20 22: "July 2022"
june 20 20 six: "JUNE2020"
june 20 22: "June 2022"
jupiter y: "Jupyter"
jupyter lab: "JupyterLab"
jurisdiction under id six: "JURISDICTION_ID"
k a f k a: "Kafka"
k b six: "KB"
k c six: "KC"
k dash means: "k-means"
k diff three: "KDiff3"
k e five: "ke"
k e m o: "kemo"
k e n n: "Kenn"
k e r a s: "keras"
k g two: "KG2"
k h six: "KH"
k i d d u s h: "kiddush"
k m five: "km"
k m l six: "KML"
k m l: "kml"
k m s six: "KMS"
k m z six: "KMZ"
k n six: "KN"
k n expanded: "Kehilat Nitzan"
k n n six: "KNN"
k o b o: "kobo"
k p i six: "KPI"
k u b i e: "Kubie"
k u n d a n: "Kundan"
k v p six: "KVP"
k v p string string: "KvpStringString"
k v p: "kvp"
ken two ens: "Kenn"
key pass: "keepass"
key set: "keyset"
key sets: "keysets"
key value pairs: "KeyValuePairs"
knack dan: "nakdan"
l a h a v: "Lahav"
l a t: "lat"
l b l: "lbl"
l c s i six: "LCSI"
l e d five: "led"
l e e o r: "Leeor"
l e n: "len"
l e v i n: "Levin"
l e v y: "Levy"
l g six: "LG"
l g a six: "LGA"
l g a under name six: "LGA_NAME"
l g a: "lga"
l g p s: "lgps"
l g t m : "LGTM"
l h s six: "LHS"
l i b: "lib"
l i d a r: "lidar"
l i n q: "linq"
l k six: "LK"
l l five: "ll"
l m five: "lm"
l m a o : "LMAO"
l m s six: "LMS"
l o a: "LoA"
l o c: "loc"
l o l: "lol"
l o s three: "LoS"
l o s six: "LOS"
l o s: "los"
l p six: "LP"
l p byte: "LPBYTE"
l p c byte: "LPCBYTE"
l p c s t r: "LPCSTR"
l p c void: "LPCVOID"
l p g s six: "LPGS"
l p t one: "LPT1"
l p void: "LPVOID"
l p w s t r: "LPWSTR"
l s five: "ls"
l s eyes : "LSIs"
l s i six: "LSI"
l s p: "lsp"
l s s a : "LSSA"
l s t m six: "LSTM"
l s t p: "lstp"
l s t: "lst"
l t d three: "Ltd"
l t e: "lte"
l t r six: "LTR"
l t r: "ltr"
l t s six: "LTS"
l y n x: "lynx"
laasot: "to do"
lambda at edge: "Lambda@Edge"
land tenure: "Land Tenure"
land v i c : "LandVIC"
laser six: "LASER"
last write time: "LastWriteTime"
lat long: "LatLong"
lat slash long: "lat/long"
latin one: "latin1"
left 80 right: "[80]"
left bracket bracket: "[["
left bracket hat: "[^"
left bracket space quote: "[ ""
left cancelled right: "[cancelled]"
left draft right: "(draft)"
left duplicate right: "[Duplicate]"
left e mail right: "(email)"
left g right: "(G)"
left hotel right: "(h)"
left hours right: "(hours)"
left in one right: "[In] "
left juliet right: "[j]"
left left p: "left("
left m right space: "[M] {Left}{Left}"
left math colon colon: "[Math]::"
left minor right: "[Minor]"
left out one right: "[Out] "
left out right: "[out] "
left p back quote: "(`"
left p i right: "(i)"
left proposed right: "[Proposed]"
left right bracket ellipses: "[...]"
left right bracket s: "[] "
left right bracket: "[]"
left right colon colon: "[]::"
left right lambda: "() => "
left right p: "()"
left star right: "(*)"
left star this right: "(*this)"
left umbrella right: "(umbrella)"
left x-ray right: "(x)"
left zero right: "[0]"
legal parcel id six: "LEGAL_PARCEL_ID"
let me know: "let me know"
let us know: "let us know"
level under geocoded code: "LEVEL_GEOCODED_CODE"
level under number six: "LEVEL_NUMBER"
license i d: "LicenseId"
light sail: "LightSail"
lima two norm: "L2-norm"
lima two: "L2"
linked in: "LinkedIn"
list bracket: "List<"
list left: "List<"
list of: "List(Of "
list type: "listType"
local d b : "LocalDB"
locality under name: "LOCALITY_NAME"
locality under neighbour: "LOCALITY_NEIGHBOUR"
locality under p i d six: "LOCALITY_PID"
lock i d three: "LocId"
lock id brian: "LocID"
lock under i dees: "LOC_IDs"
lock under id: "LOC_ID"
log four net: "log4net"
log output: "LogOutput"
lot under number six: "LOT_NUMBER"
m two: "m2"
m three dot large: "m3.large"
m a six: "MA"
m a c: "mac"
m a p i five: "mapi"
m a p i: "MAPI"
m a r 23: "MAR23"
m a r: "mar"
m a t h: "math"
m a x i: "maxi"
m audio: "M-Audio"
m b five: "mb"
m b s a : "MBSA"
m b slash s : "MB/s"
m c g: "mcg"
m c q six: "MCQ"
m connect: "Kinect"
m d b six: "MDB"
m d b: "mdb"
m d m six: "MDM"
m d u six: "MDU"
m d u under address six: "MDU_ADDRESS"
m d u under i d : "MDU_ID"
m d u: "mdu"
m d use: "MDUs"
m e d: "med"
m e m: "mem"
m e r six: "MER"
m e r a v: "Merav"
m e s s: "mess"
m e x: "mex"
m f five: "mf"
m f six: "MF"
m f a six: "MFA"
m f a delete: "MFA Delete"
m f a: "mfa"
m f c: "mfc"
m g r: "mgr"
m i c h a l: "Michal"
m i d: "mid"
m i f: "mif"
m i g: "mig"
m i m e: "mime"
m i n a: "Mina"
m i n y a n: "minyan"
m i n: "min"
m i o: "Mio"
m i s c: "misc"
m i y a: "Miya"
m k docs: "mkdocs"
m l six: "ML"
m l c six: "MLC"
m l lib: "MLLib"
m m five: "mm"
m m six: "MM"
m m c: "mmc"
m m m m : "MMMM"
m m m y y : "MMMYY"
m m o six: "MMO"
m m o: "mmo"
m m s six: "MMS"
m m: "mm"
m o d: "mod"
m p three: "mp3"
m q t six: "MQT"
m q t t six: "MQTT"
m r i six: "MRI"
m r p six: "MRP"
m r p: "mrp"
m r r six: "MRR"
m r r p six: "MRRP"
m r r: "mrr"
m r u: "mru"
m s five: "ms"
m s a six: "MSA"
m s b six: "MSB"
m s d n: "MSDN"
m s f : "MSF"
m s g box: "MsgBox"
m s g: "msg"
m s i: "msi"
m s k six: "MSK"
m s m six: "MSM"
m s s q l : "MSSQL"
m s v c: "msvc"
m slash h: "MRP/HRRL"
m t c f : "MTCF"
m t c f six: "MTCF"
m t m: "mtm"
m t o six: "MTO"
m t under six: "MT_"
m t under i d six: "MT_ID"
m to r: "M to R"
m u five: "mu"
m u k u l: "Mukul"
m v c six: "MVC"
m v c: "mvc"
m w s six: "MWS"
m w s: "mws"
m wave: "mwave"
m x net: "MXNet"
m y o b : "MYOB"
m z six: "MZ"
m z slash r z : "MZ/RZ"
maatarotze: "what do you want"
mack nard jif: "MAKNARDJIFF"
mail item one: "MailItem"
main address three: "Main Address"
main and m d u : "MainAndMdu"
main and m d u : "MAIN_AND_MDU"
main under address six: "MAIN_ADDRESS"
main under cad point: "MAIN_CAD_POINT"
main under cad polygon: "MAIN_CAD_POLYGON"
map e: "mapi"
map info: "MapInfo"
map left: "Map<"
map page: "MapPage"
map point: "MapPoint"
map reduce: "MapReduce"
map view: "MapView"
map x: "MapX"
march 20 22: "March 2022"
march 20 23: "March 2023"
margaret comma ronny: "Margaret, Ronny"
maria d b : "MariaDB"
mark down: "markdown"
market safe: "MarketSafe"
mars two: "Mars2"
mars three six: "MARS3"
mars three: "Mars3"
mars four six: "MARS4"
mars five six: "MARS5"
mars six: "MARS"
mars s three: "MarsS3"
mary am: "Maryam"
math alpha prime: "$\large a'$"
math b to the n: "$\large b^n$"
math cap juliet: "$\large J$"
math cap victor under mike: "$\large V_m$"
math epsilon: "$\large \epsilon$"
math g of z: "$\large g(z)$"
math hat two: "^2"
math hat november: "^n"
math jacks: "MathJax"
math juliet t h: "$\large j$th"
math juliet: "$\large j${Left}"
math kilo: "$\large k${Left}"
math log of x-ray: "$\large \log(x)$"
math mu: "$\large \mu$"
math november: "$\large n${Left}"
math papa under one: "$\large p_1$"
math pi of s: "$\large \pi(s)$"
math q of s a: "$\large Q(s, a)$"
math q of s prime a prime: "$\large Q(s', a')$"
math sierra prime: "$\large s'$"
math vector cap echo: "\vec E"
math vector cap foxtrot: "\vec F"
math x-ray under one: "$\large x_1$"
math x-ray under two: "$\large x_2$"
math x-ray: "$\large x${Left}"
matt s: "Mattes"
max out: "Maxout"
max under path: "MAX_PATH"
may 19: "MAY19"
may 20 19: "May 2019"
may 20 23: "May 2023"
may 20 written reasons: "MAY20_WRITTEN_REASONS"
may 20: "MAY20"
may 21: "MAY21"
may 22: "MAY22"
may 23: "MAY23"
measure dash: "Measure-"
mega pixel: "megapixel"
melbourne metro: "Melbourne Metro"
men you h: "Menucha"
menu log: "Menulog"
merge dash base: "merge-base"
merged from: "Merged from"
message box t: "MessageBox(_T(""
message box: "MessageBox"
meta data: "metadata"
method alpha: "Method A"
method bravo: "Method B"
mice six: "MICE"
micro services: "microservices"
micro v m: "microVM"
mif mid six: "MIFMID"
mind fuck: "mindfuck"
mini pro: "miniPRO"
minus one: "-1"
minus 10: "-10"
minus 15: "-15"
minus 30: "-30"
minus 35: "-35"
minus bravo space: "-b "
minus echo space: "-e "
minus foxtrot space: "-f "
minus india space: "-i "
minus kilo space: "-k "
minus papa space: "-p "
misc search commercial: "D:\_MMO\Misc\Search Commercial"
mobile pre: "MobilePre"
montefiore home: "Montefiore Home"
more telecom one: "MoreTelecom"
more telecom: "More Telecom"
mow callpoint then: "P:\_MMO\Callpoint\2020_08"
mow geoscape now: "Y:\_MMO\PSMA\2022_08"
multi a z: "Multi-AZ"
multi class: "multiclass"
multi deck: "multi-deck"
multi label: "multi-label"
multi line: "multiline"
multi polygon: "Multipolygon"
mum email: "elana.zulaikha@gmail.com"
my c v v: "295"
my email elana: "elana.zulaikha@gmail.com"
my expiry: "0423"
my gov i d : "MyGovID"
my gov: "MyGov"
my home number: "(02) 9328 2575"
my i sam: "MyISAM"
my mobile one: "0414937146"
my mobile: "0414 937 146"
my name: "Ronny Zulaikha"
my phone: "9328-2575"
my s q l three: "MySql"
my s q l six: "MYSQL"
my s q l retryable conn: "MySqlRetryableConnection"
my s q l: "MySql"
my service number: "0201333925"
my set: "MySet"
my street address woollahra: "26/297 Edgecliff Rd Woollahra"
my street address: "26/297 Edgecliff Rd"
my super: "MySuper"
my t p g number: "3572876"
my tab: "mitab"
my visa code: "533"
my visa debit: "4434600005975300"
my work number: "02 9478 7940"
n slash c: "N/C"
n a five: "na"
n a b six: "NAB"
n a b: "NAB"
n a c l six: "NACL"
n a n g: "Nang"
n a t six: "NAT"
n a t speak: "NatSpeak"
n a t: "nat"
n a v: "nav"
n b six: "NB"
n b n six: "NBN"
n b n e e one: "NbnEe"
n b n p o i: "NbnPoi"
n b n under: "NBN_"
n b n: "nbn"
n b r: "nbr"
n c h six: "NCH"
n cat: "NCAT"
n d array: "ndarray"
n e e r a j: "Neeraj"
n e f o six: "NEFO"
n e f o: "nefo"
n e melbourne: "NE Melbourne"
n e t six: "NET"
n expected exception: "[ExpectedException(typeof())]"
n f s six: "NFS"
n g r o k: "ngrok"
n g wave: "NGWave"
n i k u d: "nikud"
n i l y: "Nily"
n i m h : "NiMH"
n i t e: "nite"
n l b six: "NLB"
n l p six: "NLP"
n l p: "nlp"
n l t: "nlt"
n m b six: "NMB"
n m b l: "nmbl"
n m e a: "nmea"
n n six: "NN"
n o r m: "norm"
n o v 23: "NOV23"
n o v: "nov"
n p m: "npm"
n p o s: "npos"
n s five: "ns"
n s corp: "NSCorp"
n s w : "NSW"
n s w six: "NSW"
n s w colon s: "NSW: "
n s w comma: "NSW,"
n s w t f : "NSWTF"
n s w under: "NSW_"
n slash a: "N/A"
n swag: "NSwag"
n t five: "nt"
n t six: "NT"
n t colon s: "NT:{Space}"
n t comma: "NT,"
n t f s : "NTFS"
n t status: "NTSTATUS"
n t under: "NT_"
n test fixture: "[TestFixture]"
n u m: "num"
n under: "N_"
n unit: "NUnit"
n v a r: "nvar"
n z five: "nz"
n z s under: "NZS_"
name colin: "Colin"
name dick head: "Dezarnaulds"
name space: "namespace"
name spaces: "namespaces"
nano leaf: "nanoleaf"
nap no gnaf: "NapNoGnaf"
nav man: "Navman"
nav point: "NavPoint"
nav tech: "NAVTEQ"
near net: "Near-Net"
necks e tell: "NexeTEL"
neo four j: "Neo4j"
net seven point zero: "net7.0"
net c f : "NETCF"
net gear: "Netgear"
network a c l : "Network ACL"
new dash: "New-"
new get: "nuget"
next gen dot net: "NextGen.Net"
next gen: "NextGen"
next step: "NextStep"
nick scali: "Nick Scali"
night rider: "NiteRider"
nine bot s two: "Ninebot S2"
nine bot: "Ninebot"
no error: "NO_ERROR"
no s q l: "NoSQL"
node two i d: "Node2Id"
node dot j s: "Node.js"
node id: "NodeId"
non point one: "NonPoint"
non under six: "NON_"
nord v p n: "NordVpn"
north side: "Northside"
not now: "NotNow"
nov 20: "NOV20"
november 20 22: "November 2022"
novo tell: "Novotel"
nspector one: "Inspector"
num pie: "numpy"
number combo: "NumberCombo"
number under first six: "NUMBER_FIRST"
o a six: "OA"
o a c six: "OAC"
o a i six: "OAI"
o a u t h: "OAuth"
o auth: "OAuth"
o b i e: "Obie"
o b j: "obj"
o c i six: "OCI"
o c r six: "OCR"
o c t 18: "OCT18"
o c t six: "OCT"
o c t: "oct"
o d b c six: "ODBC"
o d b c: "odbc"
o d i: "Odi"
o data view: "```dataview{Enter}"
o f a s six: "OFAS"
o f a s: "ofas"
o f e r: "Ofer"
o f f: "off"
o g m six: "OGM"
o g r : "OGR"
o g r six: "OGR"
o g r: "ogr"
o h a n a: "Ohana"
o h and s: "OH&S"
o h s: "ohs"
o k five: "ok"
o k six: "OK"
o l a p six: "OLAP"
o l e d b : "OleDb"
o l e: "ole"
o l y a: "Olya"
o m e o: "Omeo"
o m g six: "OMG"
o media: "oOhmedia"
o n c: "onc"
o o i: "Ooi"
o o m six: "OOM"
o p five: "op"
o p g six: "OPG"
o p s six: "OPS"
o p s works: "OpsWorks"
o p s: "ops"
o p t i: "opti"
o parentheses one: "==(1)=={Space}"
o parentheses two: "==(2)=={Space}"
o parentheses three: "==(3)=={Space}"
o parentheses four: "==(4)=={Space}"
o parentheses five: "==(5)=={Space}"
o question: "> [!QUESTION] "
o quote: "> [!QUOTE] "
o r c six: "ORC"
o r g: "org"
o r i g: "orig"
o s five: "os"
o s f six: "OSF"
o s f: "osf"
o s g e o: "OSGeo"
o s i six: "OSI"
o s i: "osi"
o s r six: "OSR"
o s r core: "OsrCore"
o s r r: "osrr"
o s r: "osr"
o t six: "OT"
o t p six: "OTP"
o t t six: "OTT"
o use: "OUs"
o z: "oz"
october 20 21: "October 2021"
october 20 22: "October 2022"
off net: "Off-Net"
ole d b: "OleDb"
ole tech: "Olitech"
olive fields: "Olivefields"
on net one: "OnNet"
on net three: "OnNet"
on net six: "ONNET"
on net: "On-Net"
once off: "once-off"
one dash hot: "one-hot"
one drive: "OneDrive"
one note: "OneNote"
one time: "OneTime"
op ex: "OpEx"
open a i : "OpenAI"
open a p i : "OpenAPI"
open c v: "OpenCV"
open net c f: "OpenNETCF"
open s s l : "OpenSSL"
open search: "OpenSearch"
open shot: "OpenShot"
open x m l: "OpenXml"
optic one: "Optic"
optus under lit: "OPTUS_LIT"
or due: "OrDue"
or null one: "OrNull"
or wrong: "Orrong"
oscar under: "O_"
our key one: "OurKey"
our key: "OurKey"
out dash: "Out-"
p one three three: "p133"
p one six: "P1"
p eight 10: "P810"
p a a g e: "paage"
p a a l: "paal"
p a a s: "PaaS"
p a f six: "PAF"
p a f: "paf"
p a p s six: "PAPS"
p a r a m s: "params"
p a r a m: "param"
p a r a: "para"
p a r e n: "paren"
p a y g : "PAYG"
p and as: "Pandas"
p b five: "pb"
p b six: "PB"
p b dep six: "PBDEP"
p b dep: "pbdep"
p b e six: "PBE"
p b e: "pbe"
p b r six: "PBR"
p b under i d : "PB_ID"
p c a six: "PCA"
p c h: "pch"
p d f six: "PDF"
p d f: "pdf"
p d p six: "PDP"
p d s six: "PDS"
p d under: "PD_"
p dot x: "P.X"
p e l: "pEl"
p e m six: "PEM"
p e m: "pem"
p e n: "pen"
p e r f: "perf"
p e r i s: "Peris"
p e r p: "perp"
p e r: "per"
p f a r six: "PFAR"
p f a r: "pfar"
p f l six: "PFL"
p f l: "pfl"
p f olsen: "PF Olsen"
p f x six: "PFX"
p fishing: "phishing"
p g c six: "PGC"
p g p six: "PGP"
p h e t: "phet"
p i a : "PIA"
p i d six: "PID"
p i d s: "PIDs"
p i d: "pid"
p i i six: "PII"
p i m six: "PIM"
p i n six: "PIN"
p i n v: "pinv"
p i n: "pin"
p i p u six: "PIPU"
p i p u: "pipu"
p i p: "pip"
p i x: "pix"
p l dot: "pl."
p l t: "plt"
p m t: "pmt"
p map: "PMap"
p n g six: "PNG"
p n p six: "PNP"
p n p m: "pnpm"
p n p: "pnp"
p node: "PNode"
p o a six: "POA"
p o box three: "PoBox"
p o i six: "POI"
p o i: "poi"
p o l : "POL"
p o l y: "poly"
p o r n: "porn"
p o s six: "POS"
p o s: "pos"
p p c six: "PPC"
p p c: "ppc"
p p m: "ppm"
p p w: "ppw"
p path: "PPath"
p prams: "params"
p pumble: "Pumble"
p r six s: "PRs"
p r six: "PR"
p r e l u : "PReLU"
p r e p: "prep"
p r e v: "prev"
p r e: "pre"
p r o c: "proc"
p r o d: "prod"
p r o g: "prog"
p r o j c s: "ProjCS"
p r o j: "proj"
p r o n six: "PRON"
p r o p: "prop"
p r o t o: "proto"
p r o v: "prov"
p r o: "pro"
p r s six: "PRS"
p r s: "prs"
p s one: "ps1"
p s drive: "PSDrive"
p s m a : "psma"
p s m a six: "PSMA"
p s m a under: "PSMA_"
p s pip: "PsPip"
p s under: "PS_"
p s v six: "PSV"
p s v: "psv"
p some: "Psalm"
p t r: "ptr"
p t s d : "PTSD"
p t y three: "Pty"
p to d: "PToD"
p u r i m: "Purim"
p w d: "pwd"
p w t six: "PWT"
pack map six: "PACMAP"
page a  five: "paage"
page a six: "PAAGE"
paint dot net: "Paint.net"
paling yards: "Paling Yards"
palm pilot: "Palm Pilot"
pap com six: "PAPCOM"
pap com: "Papcom"
parcel six: "PARCEL"
parcel type code six: "PARCEL_TYPE_CODE"
parcel under i d six: "PARCEL_ID"
parcel under type six: "PARCEL_TYPE"
parentheses one: "(1)"
parentheses two: "(2)"
parentheses three: "(3)"
parentheses four: "(4)"
parentheses five: "(5)"
parentheses six: "(6)"
parentheses seven: "(7)"
parentheses eight: "(8)"
parentheses nine: "(9)"
parentheses alpha: "(A)"
parentheses bravo: "(B)"
parentheses charlie: "(C)"
park it q: "Parquet"
part of speech: "PartOfSpeech"
party q l : "PartiQL"
password less: "passwordless"
path h h c s: "c:\sw\hearhere\lib\hhcs"
path point: "PathPoint"
path program files: "c:\Program Files"
path releases: "d:\releases"
path software hear here: "c:\sw\HearHere"
path software junk: "c:\sw\junk"
path windows system 32: "c:\windows\system32"
pay  pal: "PayPal"
pea limb: "pealim"
pea under (c): "p_"
pearson view: "PearsonVUE"
peered v p c : "peered VPC"
peg e: "peggy"
pen brothers: "Penbrothers"
pepper marketing: "Pepper Marketing"
percent  sierra: "%s"
percent zero two x-ray: "%02X"
percent lima foxtrot: "%lf"
percent lima delta: "%ld"
percent x-ray: "%X"
perf mon: "perfmon"
phase one: "Phase 1"
phillips hue: "Phillips Hue"
phone rob mobile: "0410 677 285"
photo scan: "PhotoScan"
pi max: "Pimax"
pi spark: "PySpark"
picto nav item: "PictoNavItem"
picto nav: "PictoNav"
pie torch: "PyTorch"
pigeon d: "pigeoned"
pigeon ing: "pigeoning"
pin one 35 92: "95201578"
pinpoint one: "Pinpoint"
pip c lib: "PipCLib"
pip defs: "PipDefs"
pip layer: "PipLayer"
pip utility: "Pip Utility"
pipe six hundred: "|600"
pipe six: "PIPE"
pit street: "Pitt St"
place mark: "placemark"
plan bravo: "Plan B"
plug dash in: "plug-in"
plug in five: "plugin"
plug in: "plugin"
plural sight: "Pluralsight"
plus slash minus: "+/-"
pocket pc: "Pocket PC"
pod cast: "podcast"
pod casts: "podcasts"
point f: "PointF"
point in polygon: "Point in Polygon"
point in: "PointIn"
poison s: "Poisson"
poly cam: "Polycam"
poly id: "PolyId"
post back: "postback"
post gres: "Postgres"
post man: "Postman"
postal under delivery type: "POSTAL_DELIVERY_TYPE"
postcode boundaries: "Postcode Boundaries"
precisely one: "Precisely"
presto d b : "PrestoDB"
primary under address six: "PRIMARY_ADDRESS"
primary under secondary six: "PRIMARY_SECONDARY"
print f: "printf(""
private function: "Private Function "
private link: "PrivateLink"
private set: "Private Set"
pro one: "Pro"
pro leah: "Prolia"
prod one: "PROD1"
prod two: "PROD2"
program files sim spec: "c:\program files\SimSpect"
project one: "Project1"
promise left: "Promise<"
property under cad six: "PROPERTY_CAD"
prospect marketing: "Prospect Marketing"
pure energy: "PureEnergy"
pushover one: "Pushover"
put six: "PUT"
python three: "python3"
q two: "Q2"
q three: "Q3"
q four: "Q4"
q a n d a: "qanda"
q a s under: "QAS_"
q a s: "qas"
q b c c : "QBCC"
q cat: "QCAT"
q count star: "COUNT(*)"
q end if: "End If"
q format count star: "FORMAT(COUNT(*), 0)"
q g i s six: "QGIS"
q gis six : "QGIS"
q group by: "GROUP BY "
q having: "HAVING "
q l d six: "QLD"
q l d comma: "QLD,"
q l d under: "QLD_"
q l d: "qld"
q order by: "ORDER BY"
q set: "SET "
q stars: "QStarz"
q t y: "qty"
q u e: "Que"
q u i p: "Quip"
q with roll up: "WITH ROLLUP"
quebec one: "Q1"
quebec three: "Q3"
question mark mark: "??"
question mark question: "??"
quick copy: "Kwik Kopy"
quick sight q: "QuickSight Q"
quick sight: "QuickSight"
quote one quote: ""1""
quote quote semi: """;"
quote quote: """"
quote right bracket: ""]"
quote space right bracket: "" ]"
r a five: "ra"
r a six: "RA"
r a c: "rac"
r a n d: "rand"
r a p six: "RAP"
r a p: "rap"
r a z: "raz"
r and d : "R&D"
r and r: "R&R"
r b a c : "RBAC"
r b b p six: "RBBP"
r b s six: "RBS"
r c s: "rcs"
r c u six: "RCU"
r conn: "rconn"
r d a r: "rdar"
r d d six: "RDD"
r d f six: "RDF"
r d p six: "RDP"
r d p: "rdp"
r d r: "rdr"
r d s six: "RDS"
r d s: "rds"
r e c: "rec"
r e d i s: "Redis"
r e f: "ref"
r e g e x: "regex"
r e l u : "ReLU"
r e l: "rel"
r e m: "rem"
r e p o: "repo"
r e p: "rep"
r e s i: "resi"
r e s p: "resp"
r e s: "res"
r e t: "ret"
r f i six: "RFI"
r f i d : "RFID"
r f i: "rfi"
r f s six: "RFS"
r g n six: "RGN"
r h s six: "RHS"
r i a a six: "RIAA"
r i ann: "Riaan"
r i l: "ril"
r i m: "rim"
r j z dash: "rjz-"
r j z: "rjz"
r m a : "RMA"
r m c six: "RMC"
r m s six: "RMS"
r n d: "rnd"
r n enz : "RNNs"
r n n six: "RNN"
r net: "AARnet"
r o i : "ROI"
r o k: "rok"
r o l y: "roly"
r o n e n: "Ronen"
r o n i: "Roni"
r o n q 44: "ronq44"
r o n q 45: "ronq45"
r o n q: "ronq"
r o s six: "ROS"
r p data: "RP Data"
r p o six: "RPO"
r r eyes: "RRIs"
r r i six: "RRI"
r r i i d : "RRI_ID"
r s six: "RS"
r s discussions: "RS disc"
r s review: "[RS Review]"
r s t: "rst"
r s v p: "rsvp"
r slash i : "R/I"
r t a: "RTA"
r t c six: "RTC"
r t l six: "RTL"
r t l: "rtl"
r t s six: "RTS"
r to m: "R to M"
r to w: "R to W"
r x three: "Rx"
r x five: "rx"
r z two six: "RZ2"
r z six: "RZ"
r z colon: "RZ:"
r z slash alex: "RZ/Alex"
r z slash i l r : "RZ/ILR"
r z slash m z : "RZ/MZ"
r z slash y a : "RZ/YA"
r z slash: "RZ/"
r z solo: "RZ Solo"
r z under: "rz_"
ram cam six: "RAMCAM"
ram cam: "ramcam"
range hood: "rangehood"
raw m d u : "Raw MDU"
razor one: "Razor"
razor o: "Razor"
re cell: "recell"
read dash: "Read-"
read me: "readme"
ready nas: "ReadyNAS"
real sense: "RealSense"
real v n c : "RealVNC"
recognition k: "Rekognition"
record set: "recordset"
rectangle f: "RectangleF"
red shift: "Redshift"
reg big: "REGBIG"
reg bock six: "REGBOC"
reg bock: "regboc"
reg c r s: "REGCRS"
reg edit: "regedit"
reg s v r 32: "regsvr32 "
reg size: "REGSIZ"
release under id: "RELEASE_ID"
reliability under code: "RELIABILITY_CODE"
rem note: "RemNote"
remote pc: "RemotePC"
remove dash: "Remove-"
rep item: "RepItem"
res net: "ResNet"
rest six full: "RESTful"
rest six: "REST"
restart dash: "restart-"
result two: "Result2"
return value: "RetVal"
rex ray: "REX-Ray"
right angle bracket s: "> "
right brace brace: "}}"
right brace semi: "};"
right bracket bracket: "]]"
right click: "right click"
right p semi: ");"
right sizing: "rightsizing"
road six: "ROAD"
road type code six: "ROAD_TYPE_CODE"
road under pid six: "ROAD_PID"
roads under hierarchy six: "ROADS_HIERARCHY"
roads under locality line: "ROADS_LOCALITY_LINE"
rom five: "rom"
ron zulu: "ronzulu"
ronen apostrophe s: "Ronen's"
ronny slash brian: "Ronny/Brian"
ronny slash isaac: "// RZ/ILR: "
ronnys agent: "RonnysAgent"
route 53: "Route 53"
run zero under: "Run0_"
run zero: "Run0"
run one under: "Run1_"
run one: "Run1"
run two under: "Run2_"
run two: "Run2"
run three: "Run3"
run four: "Run4"
run five: "Run5"
s  card verify: "SCardVerify"
s  s  spew e: "ssscpuwe"
s  t  r: "str"
s three d: "S3d"
s three glacier: "S3 Glacier"
s three one zone: "S3 One Zone"
s three standard: "S3 Standard"
s three t a : "S3TA"
s three: "S3"
s a one five: "sa1"
s a one: "SA1"
s a two five: "sa2"
s a two six: "SA2"
s a three five: "sa3"
s a four five: "sa4"
s a five: "sa"
s a six: "SA"
s a a s: "SaaS"
s a comma: "SA,"
s a m e a c h: "sameach"
s a m l : "SAML"
s a m l six: "SAML"
s a n six: "SAN"
s a n u s: "Sanus"
s a r six: "SAR"
s a r i f: "sarif"
s a r u s h: "Sarush"
s a under: "SA_"
s a v t a: "Savta"
s a x: "sax"
s a: "sa"
s b five: "sb"
s b s six: "SBS"
s c one five: "sc1"
s c five: "sc"
s c six: "SC"
s c a: "sca"
s c base: "scbase"
s c h e d: "sched"
s c m six: "SCM"
s c o s: "scos"
s c p six: "SCP"
s c t six: "SCT"
s c t: "sct"
s card a p i: "SCardApi"
s card: "SCard"
s d card: "SD Card"
s d e six: "SDE"
s d i six: "SDI"
s d k: "SDK"
s d n six: "SDN"
s d u : "SDU"
s d u six: "SDU"
s d use: "SDUs"
s dash pro: "S-Pro"
s declare: "DECLARE "
s e five: "se"
s e c: "sec"
s e d e r: "Seder"
s e e e d: "seeed"
s e i d six: "SEID"
s e l: "sel"
s e p  22: "SEP22"
s e p 23: "SEP23"
s e p three: "Sep"
s e p: "sep"
s e q: "seq"
s e s six: "SES"
s f five: "sf"
s f six: "SF"
s f activity: "SF Activity"
s f c: "sfc"
s f i six: "SFI"
s f state: "SF State"
s f t p six: "SFTP"
s f t p: "sftp"
s f task: "SF Task"
s f under six: "SF_"
s f worker: "SF Worker"
s g s six: "SGS"
s g s economics: "SGS Economics"
s h three: "sh3"
s h a h a r: "Shahar"
s h p: "shp"
s h u l a: "Shula"
s h u l: "Shul"
s i five: "si"
s i m six: "SIM"
s i n: "sin"
s j m six: "SJM"
s l a six: "SLA"
s l a a: "slaa"
s l r six: "SLR"
s l t six: "SLT"
s lock u s b: "ssslkusb"
s m b : "SMB"
s m c lib: "smclib"
s m dash two: "SM-2"
s m s six: "SMS"
s m t p six: "SMTP"
s m t p: "smtp"
s n e h a l: "Snehal"
s n g: "sng"
s n s six: "SNS"
s n s: "sns"
s o a six: "SOA"
s o c three: "SoC"
s o f six: "SOF"
s o h o six: "SOHO"
s o n o s: "sonos"
s o w six: "SOW"
s ok: "S_OK"
s p five: "sp"
s p six: "SP"
s p eight three five three six: "SP8535"
s p a six: "SPA"
s p a h r: "Spahr"
s p c: "spc"
s p e c: "spec"
s p o f: "spof"
s p type: "SP Type"
s q k m: "sqkm"
s q l five: "sql"
s q l six: "SQL"
s q l geography: "SqlGeography"
s q l geometry: "SqlGeometry"
s q l server one: "SqlServer"
s q l: "sql"
s q light w five: "sqlitew"
s q light: "SQLite"
s q m: "sqm"
s q r t: "sqrt"
s q r: "sqr"
s q s : "SQS"
s q s six: "SQS"
s r five: "sr"
s r six: "SR"
s r c: "src"
s r i d six: "SRID"
s r i d: "srid"
s r n : "SRN"
s r n six: "SRN"
s r s algorithm: "SrsAlgorithm"
s r s: "srs"
s r settings: "SRSettings"
s r t six: "SRT"
s r t m : "SRTM"
s r t: "srt"
s r v r: "srvr"
s s a six: "SSA"
s s d one six: "SSD1"
s s d six: "SSD"
s s e : "SSE"
s s filter: "sssscflt"
s s h six: "SSH"
s s h net: "SshNet"
s s i s six: "SSIS"
s s l six: "SSL"
s s m six: "SSM"
s s m s : "SSMS"
s s o six: "SSO"
s s s six: "SSS"
s s s a: "sssa"
s s s c p s v: "ssscpsv"
s s s: "sss"
s t a t s: "stats"
s t a t: "stat"
s t d six: "STD"
s t d call: "stdcall"
s t d: "std"
s t g six: "STG"
s t l six: "STL"
s t p: "stp"
s t r: "str"
s t s six: "STS"
s t under six: "ST_"
s t under: "st_"
s t x six: "STX"
s u b l: "subl"
s u m r a: "Sumra"
s u m: "sum"
s u p six: "SUP"
s u p under: "sup_"
s u p: "sup"
s v c: "svc"
s v d six: "SVD"
s v h six: "SVH"
s v n six: "SVN"
s v n: "svn"
s v r: "svr"
s w two: "SW2"
s w five: "sw"
s w f six: "SWF"
s w l: "swl"
s y g i c: "sygic"
s y n c: "sync"
s y s: "sys"
s21: "S21"
sacks institute: "Sax Institute"
safe array: "SAFEARRAY"
sam six: "SAM"
sam ten: "Samten"
samba: "Samba"
same era: "Sameera"
san disk: "SanDisk"
saturn under c: "SATURN_C"
scale a: "Scala"
sci ends: "Sciens"
screen shot: "screenshot"
screen shots: "screenshots"
scroll bar three: "ScrollBar"
sea born: "Seaborn"
search commercial: "Search Commercial"
second s: "second"
secondary under address six: "SECONDARY_ADDRESS"
secondary under complex name: "SECONDARY_COMPLEX_NAME"
see far six: "SEIFA"
see far: "seifa"
see ya six: "SEIYA"
seg bot: "Segbot"
segway chat: "SegwayChat"
select star from: "SELECT * FROM "
semi confluence: "; Confluence"
semi emails: "; Emails"
semi g los: "; GLOS"
semi gista dash: "; GISTA-"
semi i r discussions: "; IR disc"
semi jeera six: "; JIRA"
semi r s discussions: "; RS disc"
semi s: "; "
semi sup dash 10: "; SUP-10"
semi sup dash 13: "; SUP-13"
semi sup dash two: "; SUP-2"
semi sup dash five: "; SUP-5"
semi sup dash: "; SUP-"
semi u p a support: "; UPA support"
semi various: "; Various"
semi whack dash six: "; WAQ-6"
semi whack support: "; WAQ support"
sep three: "Sep"
september 20 22: "September 2022"
sequel server: "SQL Server"
service class three: "Service Class"
service lens: "ServiceLens"
set dash: "Set-"
shalom nahag: "hello driver"
shape file one: "Shapefile"
shill off: "Chilov"
shop a docket: "Shop-A-Docket"
shop mate: "ShopMate"
shul cloud: "ShulCloud"
sierra colon back: "S:\"
sierra dot dash: "S. Dash"
sig win: "cygwin"
sigh kit learn: "scikit-learn"
signal r: "SignalR"
signer one: "Signer"
sim card: "SimCard"
single quote quote: "''"
single quote y quote: "'Y'"
sis tane: "Systane"
sketch  up: "SketchUp"
slash zero eight: "/08"
slash 100: "/100"
slash four 20 15: "/4/2015"
slash b b : "BB"
slash right angle bracket: "/>"
slash slash : "//"
slash this month: "/06/05"
smiley face: ":-)"
smote six: "SMOTE"
soar six: "SOAR"
soft max: "softmax"
soft phone: "softphone"
software a q pro: "D:\sw\callpoint\AQ Pro\trunk"
software amatek: "d:\sw\amatek\"
software callpoint: "D:\sw\Callpoint"
software d n lib: "D:\sw\callpoint\dnlib\trunk"
software hear here m p three: "C:\sw\HearHere\Experiments\mp3"
software logs: "c:\sw\logs"
software m m o config: "D:\sw\callpoint\upa\MmoConfig\trunk"
software m m o: "D:\sw\Callpoint\Upa\Mmo\trunk"
software pipu: "E:\sw\Callpoint_svn\Util\PipUtil\trunk"
software shortest path: "C:\sw\CallPoint\ShortestPath"
software u p a releases: "D:\sw\Callpoint\Upa\Upa\releases"
software u p a: "D:\sw\Callpoint\Upa\trunk"
sol jen: "Solgen"
solar p v : "Solar PV"
solar under address six: "SOLAR_ADDRESS"
solar under panel: "SOLAR_PANEL"
sound bar: "soundbar"
sound x: "Soundex"
source dash: "source-"
source safe: "SourceSafe"
spacy five: "spacy"
spacy: "spaCy"
spark three: "Spark"
spatial lite: "SpatiaLite"
spirit grow: "Spiritgrow"
spot if i: "Spotify"
stack sets: "StackSets"
staging under: "staging_"
star dot t x t space: "*.txt "
star draft star: "**draft**"
star m under p: "*m_p"
star s p u p: "* p_p"
star space: "* "
star star: "**"
start dash: "Start-"
start financial year: "1/7/2007"
state under p i d : "STATE_PID"
stats calculator: "statsCalculator"
status success: "STATUS_SUCCESS"
stop dash: "Stop-"
stop watch: "stopwatch"
strata under type: "STRATA_TYPE"
street combo name: "StreetComboName"
street frontage: "Street Frontage"
street info one: "StreetInfo"
street under line six: "STREET_LINE"
street under line pid: "STREET_LINE_PID"
street under line: "STREET_LINE"
street under locality line: "STREET_LOCALITY_LINE"
street under locality p i d : "STREET_LOCALITY_PID"
street under locality: "STREET_LOCALITY"
string builder: "StringBuilder"
string s t r: "string str"
sub address: "subaddress"
sub addresses: "subaddresses"
sub deck: "subdeck"
sub fields: "subfields"
sub folder: "subfolder"
sub item: "SubItem"
sub keys: "subkeys"
sub m g r: "SubMgr"
sub name: "subname"
sub string: "Substring"
sub tasks: "sub-tasks"
sub type: "subtype"
sub unit one: "SubUnit"
sub version: "Subversion"
succeeded six: "SUCCEEDED("
succeeded result: "SUCCEEDED(Result)"
sun dog: "Sundog"
sup dash 10 66: "SUP-1066"
sup under admin: "SUP_ADMIN"
sup under data: "SUP_DATA"
sup under geok: "SUP_GEOC"
sup under software: "SUP_SOFTWARE"
sup under whack: "SUP_WAQ"
super loop: "Superloop"
support one: "Support"
surf shark: "Surfshark"
surface cover: "Surface Cover"
surry hills: "Surry Hills"
swift x: "Swyftx"
swimming under pool six: "SWIMMING_POOL"
system net: "Systemnet"
t  zero: "T0"
t 24: "T24"
t a b: "tab"
t a n a: "Tana"
t a p o: "Tapo"
t a s six: "TAS"
t a s colon s: "TAS: "
t a s comma: "TAS,"
t a s under: "TAS_"
t a u: "tau"
t ampersand t: "T&T"
t and t state: "T&T State"
t b d six: "TBD"
t b l: "tbl"
t body: "tbody"
t c n: "tcn"
t c o : "TCO"
t c p five: "tcp"
t c p client: "TcpClient"
t c p dash: "TCP-"
t char: "TCHAR"
t d five: "td"
t d six: "TD"
t e c h: "tech"
t e m p: "temp"
t equals zero: "T=0"
t f six: "TF"
t f i d f : "TF-IDF"
t f n six: "TFN"
t f t p : "TFTP"
t file: "TFile"
t h c: "thc"
t h x: "thx"
t i five: "ti"
t i f: "tif"
t l s one point zero: "TLS 1.0"
t l s one point one: "TLS 1.1"
t l s one point two: "TLS 1.2"
t l s six: "TLS"
t l s: "tls"
t l v : "tlv"
t l v six: "TLV"
t m j six: "TMJ"
t m n e: "Tmne"
t m p: "Tmp"
t n r d six: "TNRD"
t n t five: "tnt"
t n t six: "TNT"
t node i d: "TNodeId"
t o five: "to"
t o b y: "Toby"
t o c six: "TOC"
t o colon s: "To: "
t o colon: "To:"
t o d o: "todo"
t o f: "tof"
t o g g l: "toggl"
t o n six: "TON"
t o o: "too"
t o p o: "topo"
t o t p six: "TOTP"
t p d six: "TPD"
t p g : "TPG"
t p g six: "TPG"
t p g c six: "TPGC"
t p g c: "tpgc"
t p s c: "tpsc"
t p s: "tps"
t p t: "tpt"
t p u six: "TPU"
t pass: "TPass"
t r a n s: "trans"
t s five: "ts"
t s six: "TS"
t s c: "tsc"
t s config: "tsconfig"
t s t: "tst"
t s v: "tsv"
t score: "T-Score"
t t i: "tti"
t t l six: "TTL"
t t n c f: "ttncf"
t t n: "ttn"
t t p six: "TTP"
t t s s six: "TTSS"
t u i: "tui"
t w o: "two"
t x three: "Tx"
t x five: "tx"
t x t: "txt"
tab  info: "TabInfo"
tab two tab: "tab2tab"
tab six: "TAB"
tab lu: "Tableau"
table under: "Table_"
tag six: "TAG"
tag cache: "TagCache"
tag search commercial: "Tag: Search Commercial"
task left: "Task<"
teams one: "Teams"
tell net: "telnet"
template r: "Templater"
ten knee: "Tennie"
tensor flow: "TensorFlow"
test zero zero: "Test00"
test dash: "Test-"
test h r result: "TESTHR(Result)"
test i d: "TestId"
test under: "Test_"
text box one: "TextBox"
text box: "TextBox"
text direction one: "TextDirection"
text racked: "Textract"
third t: "third"
tick tock: "TikTok"
tilde tilde: "~~"
time code: "timecode"
time codes: "timecodes"
time span: "TimeSpan"
time stamp: "timestamp"
time stream: "Timestream"
timtzotskoofim: "Go suck monkeys"
tinker pop: "TinkerPop"
to alpha: "to a"
to be: "to be"
to colon alex: "To: Alex"
to colon brian: "To: Brian"
to colon dad: "To: Dad"
to colon gahba: "To: Yael"
to colon ronny comma brian: "To: Ronny, Brian"
to do two: "to do"
to do six: "TODO"
to do colon: "TODO:"
to margaret comma brian: "To: Margaret, Brian"
to s a: "to a"
to s do: "to do"
to string: "ToString"
to the: "to the"
toble ronny: "Tobleroni"
today's date: "28/09/2020"
tom tom one: "TomTom"
tool bar: "toolbar"
top 10: "TOP 10 "
topic path one: "TopicPath"
topic path list: "TopicPathList"
tortoise s v n : "TortoiseSVN"
trans pile: "transpile"
trans topo: "TransTopo"
transport and topography: "Transport and Topography"
transport hierarchy code six: "TRANSPORT_HIERARCHY_CODE"
transport under hierarchy code: "TRANSPORT_HIERARCHY_CODE"
tree no: "Trino"
tribo electric: "triboelectric"
truth e: "truthy"
tuple string string: "TupleStringString"
type script: "TypeScript"
u two f : "U2F"
u a f six: "UAF"
u art: "UART"
u bun too: "ubuntu"
u c c six: "UCC"
u c l six: "UCL"
u c l: "ucl"
u d f six: "UDF"
u d f: "udf"
u d p six: "UDP"
u dem me: "Udemy"
u i five: "ui"
u i six: "UI"
u i a : "UIA"
u i c c five: "uicc"
u i c c six: "UICC"
u i n t 64: "UInt64"
u i n t: "UInt"
u in: "UINT"
u m l : "UML"
u m l six: "UML"
u n h c r : "UNHCR"
u n r w a : "UNRWA"
u n r w a: "unrwa"
u n s w : "UNSW"
u p a one: "UPA1"
u p a six: "UPA"
u p a filename expander: "UpaFilenameExpander"
u p a g s one: "UpaGs"
u p a release: "UPA Release"
u p a status: "UpaStatus"
u p a support: "UPA support"
u p a: "upa"
u p s six: "UPS"
u r five: "ur"
u r b: "urb"
u r elves: "URLs"
u r i: "uri"
u r l six: "URL"
u r l s: "urls"
u r l: "url"
u s five: "us"
u s b six: "USB"
u s b: "usb"
u s i d: "usid"
u s i m: "USIM"
u sim: "USIM"
u slash l six: "U/L"
u t c six: "UTC"
u t f: "utf"
u t i l s: "utils"
u t i l: "util"
u t l: "utl"
u w p: "uwp"
un initialize: "uninitialize"
un named: "unnamed"
under zero eight: "_08"
under zero nine: "_09"
under 20 15: "_2015"
under 20 21: "_2021"
under a u t h: "_AUTH"
under active: "_ACTIVE"
under address six: "_ADDRESS"
under b string: "_bstr_t"
under b u f: "_BUF"
under bravo two: "_b2"
under c p five: "_cp"
under c p six: "_CP"
under c t e : "_CTE"
under change six: "_CHANGE"
under charlie papa: "_cp"
under class six: "_CLASS"
under class under code six: "_CLASS_CODE"
under count six: "_COUNT"
under created six: "_CREATED"
under d z u: "_DzU"
under d z: "_Dz"
under d: "_D"
under delta: "_D"
under e v six: "_EV"
under e v: "_ev"
under early six: "_EARLY"
under echo: "_E"
under first six: "_FIRST"
under fixed geometries: "_FixedGeometries"
under flag six: "_FLAG"
under full: "_Full"
under g d a 20 20: "_GDA2020"
under g d a 94: "_GDA94"
under g r d: "_grd"
under group six: "_GROUP"
under i n d: "_ind"
under j t t: "_JTT"
under l o g: "_Log"
under lit six: "_LIT"
under locality six: "_LOCALITY"
under locality line: "_LOCALITY_LINE"
under m m six: "_MM"
under m m o six: "_MMO"
under m m: "_MM"
under mike: "_M"
under n b r: "_nbr"
under name six: "_NAME"
under p s m a : "_PSMA"
under p s m a six: "_PSMA"
under parcel six: "_PARCEL"
under point six: "_POINT"
under polygon six: "_POLYGON"
under polygon p i d six: "_POLYGON_PID"
under pool six: "_POOL"
under prefix six: "_PREFIX"
under q l d six: "_QLD"
under reg c r s: "_REGCRS"
under retired: "_RETIRED"
under road six: "_ROAD"
under romeo one: "_R1"
under romeo: "_R"
under run four: "_Run4"
under s t r six: "_STR"
under s: "_S"
under shape: "_Shape"
under site six: "_SITE"
under site geocode six: "_SITE_GEOCODE"
under source six: "_SOURCE"
under suffix six: "_SUFFIX"
under summary: "_Summary"
under t a b one: "_Tab"
under t a b: "_tab"
under t i f: "_tif"
under t n t six: "_TNT"
under t: "_T(""
under tab six: "_TAB"
under table six: "_TABLE"
under under huge: "__huge "
under uniform: "_U"
under v two: "_v2"
under v three: "_v3"
under v i c six: "_VIC"
under variant: "_variant_t"
under victor zero: "_v0"
under victor four: "_v4"
under victor six: "_v6"
under victor seven: "_v7"
under x-ray: "_X"
under x two: "_x2"
under x f l : "_XFL"
under x y c: "_XyC"
under x y p: "_XyP"
under zip six: "_ZIP"
under zone six: "_ZONE"
under zulu: "_Z"
underscore three: "_3"
underscore five: "_5"
underscore seven: "_7"
underscore golf: "_g"
underscore uniform: "_u"
uni card: "UniCard"
uni code: "Unicode"
uni under zone: "UNI_ZONE"
uninstall dash: "Uninstall-"
unit test: "UnitTest"
up jeep: "Abhijeet"
update data: "UpdateData("
util two: "Util2"
v one five zero: "v1.5.0"
v one one one: "v1.1.1"
v one four zero: "v1.4.0"
v one point two: "v1.2"
v two point zero: "v2.0"
v 20 19 dash one: "V2019-1"
v 20 20 dash one: "V2020-1"
v 20 20 dash two: "V2020-2"
v five: "v5"
v a six: "VA"
v a l: "val"
v a r: "var"
v b five: "vb"
v b six: "VB"
v b 66: "VB6"
v b a : "VBA"
v b a six: "VBA"
v b dot net: "VB.Net"
v b script: "vbscript"
v c six: "VC"
v c c six: "VCC"
v c c: "vcc"
v c i : "VCI"
v c p u: "vCPU"
v c p use: "vCPUs"
v constant s: "Const "
v d o : "VDO"
v d s l six: "VDSL"
v e n n: "venn"
v e n v: "venv"
v e r: "ver"
v else if: "ElseIf "
v else: "Else"
v exit sub: "Exit Sub"
v form mark: "Form!"
v g w six: "VGW"
v i c six: "VIC"
v i c under six: "VIC_"
v i c: "vic"
v i p six: "VIP"
v if not: "If Not "
v m six: "VM"
v m c six: "VMC"
v m ware: "VMWare"
v m x six: "VMX"
v m z: "VMs"
v n c: "vnc"
v o c u s: "Vocus"
v o i p: "VoIP"
v o n e x: "Vonex"
v p c six: "VPC"
v p c: "vpc"
v p n : "VPN"
v p n six: "VPN"
v p seas: "VPCs"
v r six: "VR"
v s five: "vs"
v s six: "VS"
v s code: "vscode"
v s s: "vss"
v s x f l: "VsXfl"
v t dash x: "VT-x"
v t l six: "VTL"
v vocus system: "Vocus system"
v vocus: "Vocus"
v x d six: "VXD"
value dash added: "value-added"
var char six: "VARCHAR"
vector three: "Vector3"
verbally from: "verbally from"
vertical bar done: "|Done"
vic map: "Vicmap"
victor five: "v5"
victor 17: "v17"
virtual box: "VirtualBox"
visual s v n : "VisualSVN"
vitamin kilo: "vitamin K"
vocus dash pricing: "Vocus-Pricing"
voice mail: "voicemail"
w three w p: "w3wp"
w a six: "WA"
w a comma: "WA,"
w a f six: "WAF"
w a h l: "Wahl"
w a n six: "WAN"
w a q six: "WAQ"
w a q service: "WaqService"
w a q: "waq"
w a under: "WA_"
w arrow r: "W-}R"
w c f six: "WCF"
w c f: "wcf"
w c u six: "WCU"
w d m: "WDM"
w e s six: "WES"
w e s: "wes"
w f four: "WF4"
w g s six: "WGS"
w g s 84: "WGS84"
w h q l: "WHQL"
w i k i: "wiki"
w i x: "wix"
w i z o : "WIZO"
w k b six: "WKB"
w k t six: "WKT"
w k t: "wkt"
w l six: "WL"
w m e: "wme"
w m f: "wmf"
w m p c f: "WmpCf"
w m p: "wmp"
w m s: "wms"
w m under: "WM_"
w n d: "wnd"
w o n: "Won"
w o t i f: "Wotif"
w o w six: "WOW"
w p f six: "WPF"
w p o i : "wpoi"
w p o i six: "WPOI"
w p p w: "wppw"
w s 20 22: "WS2022"
w s five: "ws"
w s a six: "WSA"
w s g six: "WSG"
w s g: "wsg"
w w w: "www"
w width: "width"
w write: "write"
walk through: "walkthrough"
watts app: "WhatsApp"
web a p i : "Web API"
web a q pro one: "WebAQPro"
web a q pro two: "WebAQPro2"
web assembly: "WebAssembly"
web cam: "webcam"
web forms one: "WebForms"
web hear here: "www.hear-here.com.au"
web site three: "WebSite"
web site: "web site"
web sockets: "WebSockets"
west connects: "WestConnex"
west end: "West End"
wez farmers: "Wesfarmers"
whack geoc: "WaqGeoc"
whack service: "WaqService"
whack support: "WAQ support"
where six s: "WHERE "
where dash: "Where-"
white list: "whitelist"
width equals 100 percent: "width=100%"
win 32: "Win32"
win error: "winerror"
win forms: "WinForms"
win zip: "WinZip"
windows 10: "Windows 10"
windows 2000: "Windows 2000"
windows 98: "Windows 98"
windows c e: "Windows CE"
windows media center: "Windows Media Center"
windows mobile: "Windows Mobile"
windows server 20 22: "Windows Server 2022"
windows x p: "Windows XP"
winter ton: "Winterton"
word shoresh grammar: "WordShoreshGrammar"
work book: "workbook"
work spaces web: "WorkSpaces Web"
work spaces: "WorkSpaces"
work tree: "worktree"
wrike k: "Wrike"
write dash: "Write-"
x-ray three: "X-Ray"
x-ray under six: "X_"
x-ray under: "x_"
x a m l six: "XAML"
x a m l: "xaml"
x attribute: "XAttribute"
x comment to do: "<!-- TODO: "
x d o c: "xdoc"
x d s l: "xdsl"
x dash 83 40: "X-8340"
x dash y six: "X-Y"
x dash y: "x-y"
x document: "XDocument"
x e tell: "Exetel"
x element: "XElement"
x f l six: "XFL"
x f l only: "XFL Only"
x f l under: "XFL_"
x f l: "xfl"
x g boost: "XGBoost"
x i a o : "XIAO"
x l color: "XLColor"
x l s x: "xlsx"
x l s: "xls"
x light: "X-Lite"
x list: "XList"
x m l : "xml"
x m l five: "xml"
x m l six: "XML"
x namespace: "XNamespace"
x o d o: "xodo"
x p six: "XP"
x p s: "xps"
x path: "XPath"
x s d six: "XSD"
x s d: "xsd"
x s l t : "XSLT"
x slash y: "x/y"
x unit: "xUnit"
x x x six: "XXX"
x x x under: "XXX_"
x y: "xy"
x zamel: "xaml"
y two k: "Y2K"
y a six: "YA"
y a m l six: "YAML"
y a m l: "yaml"
y a r d e n: "Yarden"
y a slash m z: "YA/MZ"
y a slash r z : "YA/RZ"
y c l: "ycl"
y h a t: "yhat"
y i e n: "Yien"
y list: "YList"
y m m v : "YMMV"
y o s i: "Yosi"
y u v i: "Yuvi"
y val: "Yuval"
y y six: "YY"
y y y m m : "YYYMM"
y y y y: "yyyy"
yael abraham: "Yael Abraham"
yarn six: "YARN"
you b key: "YubiKey"
you tube: "YouTube"
your car log one: "YourCarLog"
z period: "period"
z 56: "Z56"
z back quote: "backquote"
z back slash: "backslash"
z bar bar: "||"
z bar: "|"
z comma: "comma"
z dash: "dash"
z equals: "equals"
z f a : "ZFA"
z initialise: "initialize"
z minus: "minus"
z o h o: "Zoho"
z percent: "percent"
z point: "point"
z quote: "quote"
z s under: "ZS_"
z score: "Z-Score"
z semicolon: "semicolon"
z slash: "slash"
z space: "space"
z star: "star"
z t e six: "ZTE"
z tilde: "tilde"
z u l: "zul"
z underscore: "underscore"
z zango: "Zango"
zainbeayin: "Dick in your eye"
zala com: "Xalacom"
zala tan: "Xalatan"
zero x: "0x"
zip path three: "ZipPath"
p i p u six: "PIPU"