1 x: "1X"
2 f a: "2FA"
2 g 5: "2g"
2 g: "2G"
3 6 5: "365"
3 a: "3a"
3 g 5: "3g"
a 6 3 6: "A636"
a a b k: "bk"
a a p t: "aapt"
a a r x: "rx"
a b d 6: "ABD"
a b d: "abd"
a b l 6: "ABL"
a b l: "abl"
a b n 5: "abn"
a b n 6: "ABN"
a b r v: "abrv"
a b s 6: "ABS"
a b s: "abs"
a c c o r: "Accor"
a c c: "acc"
a c d c: "acdsee"
a c g 5: "acg"
a c k: "Ack"
a c l 6: "ACL"
a c m 6: "ACM"
a c n 6: "ACN"
a c n t: "acnt"
a c p i: "ACPI"
a c r 6: "ACR"
a c t 6: "ACT"
a c t s: "ACTS"
a c t: "act"
a d d 6: "ADD"
a d d r: "addr"
a d d: "add"
a d f 6: "ADF"
a d f: "adf"
a d j 6: "ADJ"
a d m 5: "adm"
a d m 6: "ADM"
a d m: "adm"
a d n 6: "ADN"
a d o 6: "ADO"
a d r s: "adrs"
a d s l 6: "ADSL"
a d s l: "adsl"
a e 6: "AE"
a f o m: "afom"
a f x: "afx"
a g l 6: "AGL"
a g m 6: "AGM"
a g r 6: "AGR"
a h 6: "AH"
a h p r a: "ahpra"
a i 6: "AI"
a i d 6: "AID"
a i d: "aid"
a k a: "aka"
a l b 6: "ALB"
a l g 6: "ALG"
a l l o c: "alloc"
a l s 6: "ALS"
a l t: "alt"
a m 6: "AM"
a m a s 6: "AMAS"
a m i 6: "AMI"
a m l 6: "AML"
a m n g 6: "AMNG"
a m s 6: "AMS"
a m s l 6: "AMSL"
a m s l: "amsl"
a n a t: "anat"
a n k i: "Anki"
a n u 6: "ANU"
a n u: "Anu"
a n z 6: "ANZ"
a o i 6: "AOI"
a p 6: "AP"
a p a 6: "APA"
a p a m d u 1: "ApaMdu"
a p a: "apa"
a p d u 6: "APDU"
a p i 6: "API"
a p i: "api"
a p p l: "appl"
a p p s: "apps"
a p p: "app"
a p t: "apt"
a q 5: "aq"
a q m s 6: "AQMS"
a q m s: "aqms"
a q p 6: "AQP"
a q p: "aqp"
a r c: "arc"
a r g s: "Args"
a r g v: "argv"
a r g: "arg"
a r i 6: "ARI"
a r n 6: "ARN"
a r n: "arn"
a s c: "asc"
a s g 6: "ASG"
a s m: "asm"
a s p: "asp"
a s s o c: "assoc"
a s t 6: "AST"
a s t: "ast"
a s y n c: "async"
a t l 5: "atl"
a t l: "ATL"
a t n: "atn"
a t o 5: "ato"
a t o 6: "ATO"
a t r 6: "ATR"
a t r: "atr"
a t s i c 6: "ATSIC"
a t t r: "attr"
a t t: "att"
a u d: "aud"
a u g: "aug"
a u s 6: "AUS"
a u s t: "aust"
a u s: "aus"
a u t h: "auth"
a u t: "aut"
a v 6: "AV"
a v g: "avg"
a v i 1: "Avi"
a v i v i: "Avivi"
a w k: "awk"
a w s 5: "aws"
a w s 6: "AWS"
a w s e c 2: "AWS EC2"
a w s e k s: "AWS EKS"
a w s s 3: "AWS S3"
a w s: "AWS"
a x 5: "ax"
a z 6: "AZ"
a z o p t: "Azopt"
b a 6: "BA"
b a l: "bal"
b a r e l: "Barel"
b a u d: "baud"
b b 6: "BB"
b e l e l i: "beleli"
b e r: "ber"
b f 6: "BF"
b i 5: "bi"
b i 6: "BI"
b i d a l: "BiDal"
b i n: "bin"
b i t: "bit"
b j 6: "BJ"
b l a h: "blah"
b l d g: "bldg"
b l d: "bld"
b l l 6: "BLL"
b l l: "bll"
b l u m: "Blum"
b o m: "bom"
b o t o 3: "boto3"
b o x: "box"
b r i t: "brit"
b s p 6: "BSP"
b s p: "bsp"
b s s: "bss"
b t n: "btn"
b t w 6: "BTW"
b u d i: "Budi"
b u f: "buf"
b u p a: "Bupa"
b u s: "bus"
c 3 s: "CCcs"
c a b s: "CAbs"
c a d 6: "CAD"
c a d: "cad"
c a f 6: "CAF"
c a l c: "calc"
c a n n: "Cann"
c a n v a: "canva"
c a r t o: "carto"
c a s 5: "cas"
c a t e g: "categ"
c a v v 6: "CAVV"
c a z: "caz"
c b 5: "cb"
c b a 6: "CBA"
c b d 6: "CBD"
c b d: "cbd"
c b f 6: "CBF"
c b t: "cbt"
c c c s: "CCcs"
c c p: "CCp"
c d k 6: "CDK"
c e r t: "cert"
c f 5: "cf"
c f 6: "CF"
c f d 6: "CFD"
c f i: "cfi"
c f s 6: "CFS"
c g t 6: "CGT"
c h a g: "chag"
c h a i: "Chai"
c h a n i: "Chani"
c h a r s: "chars"
c h a r: "char"
c h d c 6: "CHDC"
c h q: "chq"
c h r: "chr"
c h v: "chv"
c i 5: "ci"
c i d: "cid"
c i t b 6: "CITB"
c l 6: "CL"
c l a 6: "CLA"
c l a: "cla"
c l b 6: "CLB"
c l b: "clb"
c l i 6: "CLI"
c l i x m l: "clixml"
c l i: "cli"
c l y m: "Clym"
c m b: "cmb"
c m d: "cmd"
c m k 6: "CMK"
c m p: "cmp"
c n c 6: "CNC"
c n n 6: "CNN"
c n t: "cnt"
c o 2: "CO2"
c o 5: "co"
c o a 6: "COA"
c o b 6: "COB"
c o c h i: "Cochi"
c o d e t: "codet"
c o h s: "COhs"
c o l s: "cols"
c o l: "col"
c o m 6: "COM"
c o m b: "comb"
c o m m: "comm"
c o m: "com"
c o n d a: "conda"
c o n j: "conj"
c o n n: "conn"
c o n s: "cons"
c o n t: "cont"
c o n v: "conv"
c o n: "con"
c o o r d: "coord"
c o r p: "corp"
c o s: "cos"
c o t s 6: "COTS"
c p 5: "cp"
c p c s: "CpCs"
c p f d r: "CpFdr"
c p i 6: "CPI"
c p s q l: "CpSql"
c p s v n: "CpSvn"
c p t 6: "CPT"
c p t: "cpt"
c p y: "cpy"
c r 3: "Cr"
c r n t: "crnt"
c r o n: "cron"
c r p 6: "CRP"
c r s 6: "CRS"
c s 5: "cs"
c s a: "csa"
c s b 6: "CSB"
c s p: "csp"
c s r 6: "CSR"
c s s 6: "CSS"
c s s: "css"
c s v: "csv"
c t 6: "CT"
c t a p 6: "CTAP"
c t l v: "CTlv"
c t r l: "ctrl"
c t x: "ctx"
c u f a r: "Cufar"
c u r l: "curl"
c u s t: "cust"
c v 5: "cv"
c v v 6: "CVV"
c v v: "cvv"
c y b g 6: "CYBG"
d a 5: "da"
d a 6: "DA"
d a c: "dac"
d a g 6: "DAG"
d a i d: "DAId"
d a l: "dal"
d a p 6: "DAP"
d a r 6: "DAR"
d a t: "dat"
d a x 6: "DAX"
d b 5: "db"
d b a: "dba"
d b o 5: "dbo"
d b o: "dbo"
d b r: "dbr"
d b s: "dbs"
d c a 6: "DCA"
d c d 6: "DCD"
d c d: "dcd"
d d 6: "DD"
d d e: "dde"
d d k: "DDK"
d d p 6: "DDP"
d d r: "ddr"
d e c 6: "DEC"
d e c: "dec"
d e f n: "defn"
d e f s: "defs"
d e f: "def"
d e j a i: "dejai"
d e l i m: "delim"
d e l: "del"
d e m 6: "DEM"
d e m: "dem"
d e p: "dep"
d e r 6: "DER"
d e s c: "Desc"
d e s t: "dest"
d e v: "dev"
d e x a 6: "DEXA"
d f 5: "df"
d f 6: "DF"
d f c e 6: "DFCE"
d f e i t: "dfeit"
d f t: "dft"
d g v: "dgv"
d h c p 6: "DHCP"
d h l 6: "DHL"
d i b: "DIB"
d i c t: "dict"
d i d 6: "DID"
d i f f: "diff"
d i j k: "dijk"
d i m a: "Dima"
d i r s: "dirs"
d i r: "dir"
d i s p: "disp"
d i s t: "dist"
d i v: "div"
d k i m 6: "DKIM"
d l g: "dlg"
d l l 6: "DLL"
d l l: "dll"
d l p 6: "DLP"
d m s 6: "DMS"
d n 7 l i b: "Dn7Lib"
d n l i b: "DnLib"
d n s 6: "DNS"
d n s: "dns"
d o 5: "do"
d o b 6: "DOB"
d o c s: "docs"
d o c: "doc"
d o d: "dod"
d o f 6: "DOF"
d o m: "dom"
d o n t: "dont"
d p i d 6: "DPID"
d p i d: "dpid"
d p i: "dpi"
d q n 6: "DQN"
d r 5: "dr"
d r 6: "DR"
d r e m e l: "dremel"
d r o r: "Dror"
d r p 6: "DRP"
d r s 6: "DRS"
d s l 6: "DSL"
d s l a m: "dslam"
d s m 6: "DSM"
d u b: "dub"
d u e: "due"
d u i: "dui"
d v d 5: "dvd"
e b 6: "EB"
e b s 6: "EBS"
e c 2 6: "EC2"
e c 2: "EC2"
e c 6: "EC"
e c g 1: "ECG-1"
e c g 4: "ECG-4"
e c g 6: "ECG"
e c g 7: "ECG-7"
e c g 9: "ECG-9"
e c g: "ecg"
e c r 6: "ECR"
e c s 6: "ECS"
e d t: "edt"
e d v 6: "EDV"
e e 5: "ee"
e e 6: "EE"
e e a s: "eeas"
e e r: "eer"
e f 5: "ef"
e f a r r: "EfArr"
e f a s: "efas"
e f d i r: "EfDir"
e f d: "efd"
e f p b r: "EfPbr"
e f s 6: "EFS"
e g g: "egg"
e k g 6: "EKG"
e k s 6: "EKS"
e l 5: "el"
e l b 6: "ELB"
e l e y: "Eley"
e l i e: "Elie"
e l i: "Eli"
e l p i 6: "ELPI"
e m c 6: "EMC"
e m o j i: "emoji"
e m r 6: "EMR"
e m r: "emr"
e n t 6: "ENT"
e n t s: "ents"
e n t: "ent"
e n u m: "enum"
e n v: "env"
e o f 6: "EOF"
e o f: "eof"
e o l 6: "EOL"
e p l b 6: "EPLB"
e p s g 6: "EPSG"
e q 5: "eq"
e q: "eq"
e r c p 6: "ERCP"
e r e v: "erev"
e r f s: "erfs"
e r r s t r: "ErrStr"
e r r: "err"
e s a 6: "ESA"
e s a: "esa"
e s r i 5: "esri"
e s r i: "esri"
e t a 6: "ETA"
e t f 6: "ETF"
e t l 6: "ETL"
e t s i 6: "ETSI"
e t s i: "etsi"
e t u: "etu"
e v 5: "ev"
e v 6: "EV"
e v a l: "eval"
e v c 3: "evc3"
e v c: "evc"
e v t: "evt"
e w k b 6: "EWKB"
e x 5: "ex"
e x c: "exc"
e x e c: "exec"
e x e r 6: "EXER"
e x e: "exe"
e x p r: "expr"
e x p: "exp"
e x t: "ext"
e y e: "eye"
e y l o n: "Eylon"
e z 6: "EZ"
f a a s: "FaaS"
f a q: "FAQ"
f a r 6: "FAR"
f c p 6: "FCP"
f c p: "fcp"
f c s 6: "FCS"
f d 6: "FD"
f d c a 6: "FDCA"
f d r 6: "FDR"
f d s 6: "FDS"
f d s: "fds"
f e 5: "fe"
f e b: "feb"
f e p 6: "FEP"
f i f o 6: "FIFO"
f i f o: "fifo"
f i l: "fil"
f l i r: "flir"
f l u: "flu"
f m 5: "fm"
f m 6: "FM"
f m e 6: "FME"
f m o 6: "FMO"
f m o d: "fmod"
f n 5: "fn"
f n a 6: "FNA"
f n n 6: "FNN"
f o f i: "fofi"
f o i 6: "FOI"
f o i: "foi"
f o r e: "fore"
f o r: "for"
f p 5: "fp"
f p l: "fpl"
f q d n 6: "FQDN"
f r e q: "freq"
f r m: "frm"
f s 5: "fs"
f s a 6: "FSA"
f s a m 6: "FSAM"
f s a m: "fsam"
f s a: "fsa"
f s r s 6: "FSRS"
f t p: "ftp"
f t t b: "fttb"
f t t c 6: "FTTC"
f t t n 6: "FTTN"
f t t n: "fttn"
f t t p 6: "FTTP"
f t t p: "fttp"
f t t x: "fttx"
f u n c: "func"
g a 6: "GA"
g a d: "gad"
g a l i a: "Galia"
g a l i t: "Galit"
g a l i: "Gali"
g b 6: "GB"
g b l: "gbl"
g b: "gb"
g c 5: "gc"
g c c s a: "gccsa"
g d a l 6: "GDAL"
g d a l: "gdal"
g d b 6: "GDB"
g d b: "gdb"
g d i 5: "gdi"
g e d 2: "ged2"
g e d: "ged"
g e n: "gen"
g e o c: "geoc"
g e o m: "geom"
g e o: "geo"
g f c: "gfc"
g g 6: "GG"
g g a 6: "GGA"
g g m 6: "GGM"
g g o x 6: "GGOX"
g g t 6: "GGT"
g h d 6: "GHD"
g h g 6: "GHG"
g i 5: "gi"
g i 6: "GI"
g i r i: "Giri"
g i s 5: "gis"
g i s 6: "GIS"
g i t: "git"
g n a f 6: "GNAF"
g n a f: "gnaf"
g o t o: "goto"
g o x 6: "GOX"
g p 2 5: "gp2"
g p 3 5: "gp3"
g p 6: "GP"
g p s 5: "gps"
g p t 3: "GPT-3"
g p t 6: "GPT"
g r c 6: "GRC"
g r d 6: "GRD"
g r d: "grd"
g r e p: "grep"
g r p: "grp"
g r u 6: "GRU"
g s 6: "GS"
g s i 6: "GSI"
g s m 5: "gsm"
g s s u 6: "GSSU"
g s s u: "gssu"
g s t: "GST"
g t e: "gte"
g t r 6: "GTR"
g u i 5: "gui"
g u i 6: "GUI"
g u i d 6: "GUID"
g u i: "gui"
g v x: "gvx"
g w l b 6: "GWLB"
g w l: "gwl"
h a 3: "Ha"
h a m a s: "Hamas"
h a t: "hat"
h c f 6: "HCF"
h c t: "HCT"
h d d 6: "HDD"
h d f s 6: "HDFS"
h e c 6: "HEC"
h e x: "hex"
h e y: "hey"
h f c 6: "HFC"
h f c: "hfc"
h f l 1 6: "HFL1"
h f l 6: "HFL"
h f l p f l 3: "HflPfl"
h f l: "hfl"
h g o x 6: "HGOX"
h g r: "hgr"
h h 5: "hh"
h h c s: "HhCs"
h h g p s: "HhGps"
h h m: "hhm"
h h p: "hhp"
h h t t: "hhtt"
h h t: "hht"
h i n 6: "HIN"
h i s t: "hist"
h m d 6: "HMD"
h o u z z: "houzz"
h p c 6: "HPC"
h p s 6: "HPS"
h r e f: "href"
h r r l 6: "HRRL"
h r r l: "hrrl"
h s l 6: "HSL"
h t m l 6: "HTML"
h t m l: "html"
h t t p 6: "HTTP"
h t t p s 6: "HTTPS"
h t t p s: "https"
h t t p: "http"
h t w 6: "HTW"
h w l 6: "HWL"
h w n d 6: "HWND"
h x 5: "hx"
i 1 6 7: "i167"
i a 6: "IA"
i a a s: "IaaS"
i a c: "IaC"
i a m 6: "IAM"
i c r 6: "ICR"
i c r: "icr"
i d 5: "id"
i d 6: "ID"
i d d 6: "IDD"
i d d: "idd"
i d e n t: "ident"
i d f 6: "IDF"
i d o k: "IDOK"
i d s 6: "IDS"
i d x: "idx"
i e 7: "IE7"
i g 5: "ig"
i g i s: "IGis"
i g w 6: "IGW"
i h h: "IHh"
i i c 6: "IIC"
i i f: "iif"
i i s 6: "IIS"
i l d a s m: "ildasm"
i l r 6: "ILR"
i m g: "img"
i m h o 6: "IMHO"
i m o 6: "IMO"
i m p l: "impl"
i m u 6: "IMU"
i m u t: "imut"
i n c i t s: "incits"
i n c: "inc"
i n f o: "info"
i n f: "inf"
i n g 6: "ING"
i n g: "ing"
i n i t: "init"
i n m: "inm"
i n s 5: "ins"
i n s 6: "INS"
i n s t: "inst"
i n s: "ins"
i n t l: "intl"
i n t p t r: "IntPtr"
i n t: "int"
i o 1: "io1"
i o 2: "io2"
i o 5: "io"
i o c: "IoC"
i o t 3: "IoT"
i p 5: "ip"
i p v 4: "IPv4"
i p v 6: "IPv6"
i q r 6: "IQR"
i r p: "irp"
i s o 6: "ISO"
i s o: "iso"
i s r 6: "ISR"
i s r s: "ISrs"
i s r: "isr"
i t 6: "IT"
i t i l 6: "ITIL"
i t r o 6: "ITRO"
i v l: "ivl"
i w m 6: "IWM"
j a b r a: "jabra"
j a n: "jan"
j c a 6: "JCA"
j e s t: "Jest"
j g 6: "JG"
j i b i n: "Jibin"
j i t: "jit"
j j 6: "JJ"
j l l 6: "JLL"
j o n o: "Jono"
j p e g: "jpeg"
j q l: "jql"
j s 5: "js"
j s o n: "json"
j t t 6: "JTT"
j t t: "jtt"
j u l a i: "Julai"
j u l: "jul"
j u n: "jun"
j v 6: "JV"
j w t 6: "JWT"
k a f k a: "Kafka"
k b 6: "KB"
k c 6: "KC"
k e 5: "ke"
k e m o: "kemo"
k e n n: "Kenn"
k e r a s: "keras"
k g 2: "KG2"
k h 6: "KH"
k i d d u s h: "kiddush"
k m 5: "km"
k m l 6: "KML"
k m l: "kml"
k m s 6: "KMS"
k m z 6: "KMZ"
k n 6: "KN"
k n n 6: "KNN"
k o b o: "kobo"
k p i 6: "KPI"
k u b i e: "Kubie"
k u n d a n: "Kundan"
k v p 6: "KVP"
k v p: "kvp"
l a h a v: "Lahav"
l a t: "lat"
l b l: "lbl"
l c s i 6: "LCSI"
l e d 5: "led"
l e e o r: "Leeor"
l e n: "len"
l e v i n: "Levin"
l e v y: "Levy"
l g 6: "LG"
l g a 6: "LGA"
l g a: "lga"
l g p s: "lgps"
l h s 6: "LHS"
l i b: "lib"
l i d a r: "lidar"
l i n q: "linq"
l k 6: "LK"
l l 5: "ll"
l m 5: "lm"
l m s 6: "LMS"
l o a: "LoA"
l o c: "loc"
l o l: "lol"
l o s 3: "LoS"
l o s 6: "LOS"
l o s: "los"
l p 6: "LP"
l p c s t r: "LPCSTR"
l p g s 6: "LPGS"
l p t 1: "LPT1"
l p w s t r: "LPWSTR"
l s 5: "ls"
l s i 6: "LSI"
l s p: "lsp"
l s t m 6: "LSTM"
l s t p: "lstp"
l s t: "lst"
l t d 3: "Ltd"
l t e: "lte"
l t r 6: "LTR"
l t r: "ltr"
l t s 6: "LTS"
l y n x: "lynx"
m 2: "m2"
m a 6: "MA"
m a c: "mac"
m a p i 5: "mapi"
m a p i: "MAPI"
m a r: "mar"
m a t h: "math"
m a x i: "maxi"
m b 5: "mb"
m c g: "mcg"
m c q 6: "MCQ"
m d b 6: "MDB"
m d b: "mdb"
m d m 6: "MDM"
m d u 6: "MDU"
m d u: "mdu"
m e d: "med"
m e m: "mem"
m e r 6: "MER"
m e r a v: "Merav"
m e s s: "mess"
m e x: "mex"
m f 5: "mf"
m f 6: "MF"
m f a 6: "MFA"
m f a: "mfa"
m f c: "mfc"
m g r: "mgr"
m i c h a l: "Michal"
m i d: "mid"
m i f: "mif"
m i g: "mig"
m i m e: "mime"
m i n a: "Mina"
m i n y a n: "minyan"
m i n: "min"
m i o: "Mio"
m i s c: "misc"
m i y a: "Miya"
m l 6: "ML"
m l c 6: "MLC"
m m 5: "mm"
m m 6: "MM"
m m c: "mmc"
m m o 6: "MMO"
m m o: "mmo"
m m s 6: "MMS"
m m: "mm"
m o d: "mod"
m p 3: "mp3"
m q t 6: "MQT"
m q t t 6: "MQTT"
m r i 6: "MRI"
m r p 6: "MRP"
m r p: "mrp"
m r r 6: "MRR"
m r r p 6: "MRRP"
m r r: "mrr"
m r u: "mru"
m s 5: "ms"
m s a 6: "MSA"
m s b 6: "MSB"
m s d n: "MSDN"
m s g: "msg"
m s i: "msi"
m s k 6: "MSK"
m s m 6: "MSM"
m s v c: "msvc"
m t c f 6: "MTCF"
m t m: "mtm"
m t o 6: "MTO"
m u 5: "mu"
m u k u l: "Mukul"
m v c 6: "MVC"
m v c: "mvc"
m w s 6: "MWS"
m w s: "mws"
m z 6: "MZ"
n a 5: "na"
n a b 6: "NAB"
n a b: "NAB"
n a c l 6: "NACL"
n a n g: "Nang"
n a t 6: "NAT"
n a t: "nat"
n a v: "nav"
n b 6: "NB"
n b n 6: "NBN"
n b n e e 1: "NbnEe"
n b n p o i: "NbnPoi"
n b n: "nbn"
n b r: "nbr"
n c h 6: "NCH"
n e e r a j: "Neeraj"
n e f o 6: "NEFO"
n e f o: "nefo"
n e t 6: "NET"
n f s 6: "NFS"
n g r o k: "ngrok"
n i k u d: "nikud"
n i l y: "Nily"
n i t e: "nite"
n l b 6: "NLB"
n l p 6: "NLP"
n l p: "nlp"
n l t: "nlt"
n m b 6: "NMB"
n m b l: "nmbl"
n m e a: "nmea"
n n 6: "NN"
n o r m: "norm"
n o v: "nov"
n p m: "npm"
n p o s: "npos"
n s 5: "ns"
n s w 6: "NSW"
n t 5: "nt"
n t 6: "NT"
n u m: "num"
n v a r: "nvar"
n z 5: "nz"
o a 6: "OA"
o a c 6: "OAC"
o a i 6: "OAI"
o a u t h: "OAuth"
o b i e: "Obie"
o b j: "obj"
o c i 6: "OCI"
o c r 6: "OCR"
o c t 6: "OCT"
o c t: "oct"
o d b c 6: "ODBC"
o d b c: "odbc"
o d i: "Odi"
o f a s 6: "OFAS"
o f a s: "ofas"
o f e r: "Ofer"
o f f: "off"
o g m 6: "OGM"
o g r 6: "OGR"
o g r: "ogr"
o h a n a: "Ohana"
o h s: "ohs"
o k 5: "ok"
o k 6: "OK"
o l a p 6: "OLAP"
o l e: "ole"
o l y a: "Olya"
o m e o: "Omeo"
o m g 6: "OMG"
o n c: "onc"
o o i: "Ooi"
o o m 6: "OOM"
o p 5: "op"
o p g 6: "OPG"
o p s 6: "OPS"
o p s: "ops"
o p t i: "opti"
o r c 6: "ORC"
o r g: "org"
o r i g: "orig"
o s 5: "os"
o s f 6: "OSF"
o s f: "osf"
o s g e o: "OSGeo"
o s i 6: "OSI"
o s i: "osi"
o s r 6: "OSR"
o s r r: "osrr"
o s r: "osr"
o t 6: "OT"
o t p 6: "OTP"
o t t 6: "OTT"
o z: "oz"
p 1 3 3: "p133"
p 1 6: "P1"
p a a g e: "paage"
p a a l: "paal"
p a a s: "PaaS"
p a f 6: "PAF"
p a f: "paf"
p a p s 6: "PAPS"
p a r a m s: "params"
p a r a m: "param"
p a r a: "para"
p a r e n: "paren"
p b 5: "pb"
p b 6: "PB"
p b e 6: "PBE"
p b e: "pbe"
p b r 6: "PBR"
p c a 6: "PCA"
p c h: "pch"
p d f 6: "PDF"
p d f: "pdf"
p d p 6: "PDP"
p d s 6: "PDS"
p e l: "pEl"
p e m 6: "PEM"
p e m: "pem"
p e n: "pen"
p e r f: "perf"
p e r i s: "Peris"
p e r p: "perp"
p e r: "per"
p f a r 6: "PFAR"
p f a r: "pfar"
p f l 6: "PFL"
p f l: "pfl"
p f x 6: "PFX"
p g c 6: "PGC"
p g p 6: "PGP"
p h e t: "phet"
p i d 6: "PID"
p i d s: "PIDs"
p i d: "pid"
p i i 6: "PII"
p i m 6: "PIM"
p i n 6: "PIN"
p i n v: "pinv"
p i n: "pin"
p i p u 6: "PIPU"
p i p u: "pipu"
p i p: "pip"
p i x: "pix"
p l t: "plt"
p m t: "pmt"
p n g 6: "PNG"
p n p 6: "PNP"
p n p m: "pnpm"
p n p: "pnp"
p o a 6: "POA"
p o i 6: "POI"
p o i: "poi"
p o l y: "poly"
p o r n: "porn"
p o s 6: "POS"
p o s: "pos"
p p c 6: "PPC"
p p c: "ppc"
p p m: "ppm"
p p w: "ppw"
p r 6 s: "PRs"
p r 6: "PR"
p r e p: "prep"
p r e v: "prev"
p r e: "pre"
p r o c: "proc"
p r o d: "prod"
p r o g: "prog"
p r o j c s: "ProjCS"
p r o j: "proj"
p r o n 6: "PRON"
p r o p: "prop"
p r o t o: "proto"
p r o v: "prov"
p r o: "pro"
p r s 6: "PRS"
p r s: "prs"
p s 1: "ps1"
p s m a 6: "PSMA"
p s v 6: "PSV"
p s v: "psv"
p t r: "ptr"
p t y 3: "Pty"
p u r i m: "Purim"
p w d: "pwd"
p w t 6: "PWT"
q 2: "Q2"
q 3: "Q3"
q 4: "Q4"
q a n d a: "qanda"
q a s: "qas"
q g i s 6: "QGIS"
q l d 6: "QLD"
q l d: "qld"
q t y: "qty"
q u e: "Que"
q u i p: "Quip"
r a 5: "ra"
r a 6: "RA"
r a c: "rac"
r a n d: "rand"
r a p 6: "RAP"
r a p: "rap"
r a z: "raz"
r b b p 6: "RBBP"
r b s 6: "RBS"
r c s: "rcs"
r c u 6: "RCU"
r d a r: "rdar"
r d d 6: "RDD"
r d f 6: "RDF"
r d p 6: "RDP"
r d p: "rdp"
r d r: "rdr"
r d s 6: "RDS"
r d s: "rds"
r e c: "rec"
r e d i s: "Redis"
r e f: "ref"
r e g e x: "regex"
r e l: "rel"
r e m: "rem"
r e p o: "repo"
r e p: "rep"
r e s i: "resi"
r e s p: "resp"
r e s: "res"
r e t: "ret"
r f i 6: "RFI"
r f i: "rfi"
r f s 6: "RFS"
r g n 6: "RGN"
r h s 6: "RHS"
r i a a 6: "RIAA"
r i l: "ril"
r i m: "rim"
r j z: "rjz"
r m c 6: "RMC"
r m s 6: "RMS"
r n d: "rnd"
r n n 6: "RNN"
r o k: "rok"
r o l y: "roly"
r o n e n: "Ronen"
r o n i: "Roni"
r o n q: "ronq"
r o s 6: "ROS"
r p o 6: "RPO"
r r i 6: "RRI"
r s 6: "RS"
r s t: "rst"
r s v p: "rsvp"
r t a: "RTA"
r t c 6: "RTC"
r t l 6: "RTL"
r t l: "rtl"
r t s 6: "RTS"
r x 3: "Rx"
r x 5: "rx"
r z 2 6: "RZ2"
r z 6: "RZ"
s 3 d: "S3d"
s 3: "S3"
s a 1 5: "sa1"
s a 1: "SA1"
s a 2 5: "sa2"
s a 2 6: "SA2"
s a 3 5: "sa3"
s a 4 5: "sa4"
s a 5: "sa"
s a 6: "SA"
s a a s: "SaaS"
s a m e a c h: "sameach"
s a m l 6: "SAML"
s a n 6: "SAN"
s a n u s: "Sanus"
s a r 6: "SAR"
s a r i f: "sarif"
s a r u s h: "Sarush"
s a v t a: "Savta"
s a x: "sax"
s a: "sa"
s b 5: "sb"
s b s 6: "SBS"
s c 1 5: "sc1"
s c 5: "sc"
s c 6: "SC"
s c a: "sca"
s c h e d: "sched"
s c m 6: "SCM"
s c o s: "scos"
s c p 6: "SCP"
s c t 6: "SCT"
s c t: "sct"
s d e 6: "SDE"
s d i 6: "SDI"
s d k: "SDK"
s d n 6: "SDN"
s d u 6: "SDU"
s e 5: "se"
s e c: "sec"
s e d e r: "Seder"
s e e e d: "seeed"
s e i d 6: "SEID"
s e l: "sel"
s e p 3: "Sep"
s e p: "sep"
s e q: "seq"
s e s 6: "SES"
s f 5: "sf"
s f 6: "SF"
s f c: "sfc"
s f i 6: "SFI"
s f t p 6: "SFTP"
s f t p: "sftp"
s g s 6: "SGS"
s h 3: "sh3"
s h a h a r: "Shahar"
s h p: "shp"
s h u l a: "Shula"
s h u l: "Shul"
s i 5: "si"
s i m 6: "SIM"
s i n: "sin"
s j m 6: "SJM"
s l a 6: "SLA"
s l a a: "slaa"
s l r 6: "SLR"
s l t 6: "SLT"
s m s 6: "SMS"
s m t p 6: "SMTP"
s m t p: "smtp"
s n e h a l: "Snehal"
s n g: "sng"
s n s 6: "SNS"
s n s: "sns"
s o a 6: "SOA"
s o c 3: "SoC"
s o f 6: "SOF"
s o h o 6: "SOHO"
s o n o s: "sonos"
s o w 6: "SOW"
s p 5: "sp"
s p 6: "SP"
s p 8 3 5 3 6: "SP8535"
s p a 6: "SPA"
s p a h r: "Spahr"
s p c: "spc"
s p e c: "spec"
s p o f: "spof"
s q k m: "sqkm"
s q l 5: "sql"
s q l 6: "SQL"
s q l: "sql"
s q m: "sqm"
s q r t: "sqrt"
s q r: "sqr"
s q s 6: "SQS"
s r 5: "sr"
s r 6: "SR"
s r c: "src"
s r i d 6: "SRID"
s r i d: "srid"
s r n 6: "SRN"
s r s: "srs"
s r t 6: "SRT"
s r t: "srt"
s r v r: "srvr"
s s a 6: "SSA"
s s d 1 6: "SSD1"
s s d 6: "SSD"
s s h 6: "SSH"
s s i s 6: "SSIS"
s s l 6: "SSL"
s s m 6: "SSM"
s s o 6: "SSO"
s s s 6: "SSS"
s s s a: "sssa"
s s s c p s v: "ssscpsv"
s s s: "sss"
s t a t s: "stats"
s t a t: "stat"
s t d 6: "STD"
s t d: "std"
s t g 6: "STG"
s t l 6: "STL"
s t p: "stp"
s t r: "str"
s t s 6: "STS"
s t x 6: "STX"
s u b l: "subl"
s u m r a: "Sumra"
s u m: "sum"
s u p 6: "SUP"
s u p: "sup"
s v c: "svc"
s v d 6: "SVD"
s v h 6: "SVH"
s v n 6: "SVN"
s v n: "svn"
s v r: "svr"
s w 2: "SW2"
s w 5: "sw"
s w f 6: "SWF"
s w l: "swl"
s y g i c: "sygic"
s y n c: "sync"
s y s: "sys"
t a b: "tab"
t a n a: "Tana"
t a p o: "Tapo"
t a s 6: "TAS"
t a u: "tau"
t b d 6: "TBD"
t b l: "tbl"
t c n: "tcn"
t c p 5: "tcp"
t d 5: "td"
t d 6: "TD"
t e c h: "tech"
t e m p: "temp"
t f 6: "TF"
t f n 6: "TFN"
t h c: "thc"
t h x: "thx"
t i 5: "ti"
t i f: "tif"
t l s 6: "TLS"
t l s: "tls"
t l v 6: "TLV"
t m j 6: "TMJ"
t m n e: "Tmne"
t m p: "Tmp"
t n r d 6: "TNRD"
t n t 5: "tnt"
t n t 6: "TNT"
t o 5: "to"
t o b y: "Toby"
t o c 6: "TOC"
t o d o: "todo"
t o f: "tof"
t o g g l: "toggl"
t o n 6: "TON"
t o o: "too"
t o p o: "topo"
t o t p 6: "TOTP"
t p d 6: "TPD"
t p g 6: "TPG"
t p g c 6: "TPGC"
t p g c: "tpgc"
t p s c: "tpsc"
t p s: "tps"
t p t: "tpt"
t p u 6: "TPU"
t r a n s: "trans"
t s 5: "ts"
t s 6: "TS"
t s c: "tsc"
t s t: "tst"
t s v: "tsv"
t t i: "tti"
t t l 6: "TTL"
t t n c f: "ttncf"
t t n: "ttn"
t t p 6: "TTP"
t t s s 6: "TTSS"
t u i: "tui"
t w o: "two"
t x 3: "Tx"
t x 5: "tx"
t x t: "txt"
u a f 6: "UAF"
u c c 6: "UCC"
u c l 6: "UCL"
u c l: "ucl"
u d f 6: "UDF"
u d f: "udf"
u d p 6: "UDP"
u i 5: "ui"
u i 6: "UI"
u i c c 5: "uicc"
u i c c 6: "UICC"
u i n t: "UInt"
u m l 6: "UML"
u n r w a: "unrwa"
u p a 1: "UPA1"
u p a 6: "UPA"
u p a g s 1: "UpaGs"
u p a: "upa"
u p s 6: "UPS"
u r 5: "ur"
u r b: "urb"
u r i: "uri"
u r l 6: "URL"
u r l s: "urls"
u r l: "url"
u s 5: "us"
u s b 6: "USB"
u s b: "usb"
u s i d: "usid"
u s i m: "USIM"
u t c 6: "UTC"
u t f: "utf"
u t i l s: "utils"
u t i l: "util"
u t l: "utl"
u w p: "uwp"
v 1 5 0: "v1.5.0"
v 1 1 1: "v1.1.1"
v 1 4 0: "v1.4.0"
v 5: "v5"
v a 6: "VA"
v a l: "val"
v a r: "var"
v b 5: "vb"
v b 6: "VB"
v b a 6: "VBA"
v c 6: "VC"
v c c 6: "VCC"
v c c: "vcc"
v c p u: "vCPU"
v d s l 6: "VDSL"
v e n n: "venn"
v e n v: "venv"
v e r: "ver"
v g w 6: "VGW"
v i c 6: "VIC"
v i c: "vic"
v i p 6: "VIP"
v m 6: "VM"
v m c 6: "VMC"
v m x 6: "VMX"
v m z: "VMs"
v n c: "vnc"
v o c u s: "Vocus"
v o i p: "VoIP"
v o n e x: "Vonex"
v p c 6: "VPC"
v p c: "vpc"
v p n 6: "VPN"
v r 6: "VR"
v s 5: "vs"
v s 6: "VS"
v s s: "vss"
v s x f l: "VsXfl"
v t l 6: "VTL"
v x d 6: "VXD"
w 3 w p: "w3wp"
w a 6: "WA"
w a f 6: "WAF"
w a h l: "Wahl"
w a n 6: "WAN"
w a q 6: "WAQ"
w a q: "waq"
w c f 6: "WCF"
w c f: "wcf"
w c u 6: "WCU"
w d m: "WDM"
w e s 6: "WES"
w e s: "wes"
w f 4: "WF4"
w g s 6: "WGS"
w h q l: "WHQL"
w i k i: "wiki"
w i x: "wix"
w k b 6: "WKB"
w k t 6: "WKT"
w k t: "wkt"
w l 6: "WL"
w m e: "wme"
w m f: "wmf"
w m p c f: "WmpCf"
w m p: "wmp"
w m s: "wms"
w n d: "wnd"
w o n: "Won"
w o t i f: "Wotif"
w o w 6: "WOW"
w p f 6: "WPF"
w p o i 6: "WPOI"
w p p w: "wppw"
w s 5: "ws"
w s a 6: "WSA"
w s g 6: "WSG"
w s g: "wsg"
w w w: "www"
x a m l 6: "XAML"
x a m l: "xaml"
x d o c: "xdoc"
x d s l: "xdsl"
x f l 6: "XFL"
x f l: "xfl"
x l s x: "xlsx"
x l s: "xls"
x m l 5: "xml"
x m l 6: "XML"
x o d o: "xodo"
x p 6: "XP"
x p s: "xps"
x s d 6: "XSD"
x s d: "xsd"
x x x 6: "XXX"
x y: "xy"
y 2 k: "Y2K"
y a 6: "YA"
y a m l 6: "YAML"
y a m l: "yaml"
y a r d e n: "Yarden"
y c l: "ycl"
y h a t: "yhat"
y i e n: "Yien"
y o s i: "Yosi"
y u v i: "Yuvi"
y y 6: "YY"
y y y y: "yyyy"
z o h o: "Zoho"
z t e 6: "ZTE"
z u l: "zul"
p i p u 6: "PIPU"