one x: "1X"
two f a: "2FA"
two g five: "2g"
two g: "2G"
three six five: "365"
three a: "3a"
three g five: "3g"
a six three six: "A636"
a a b k: "bk"
a a p t: "aapt"
a a r x: "rx"
a b d six: "ABD"
a b d: "abd"
a b l six: "ABL"
a b l: "abl"
a b n five: "abn"
a b n six: "ABN"
a b r v: "abrv"
a b s six: "ABS"
a b s: "abs"
a c c o r: "Accor"
a c c: "acc"
a c d c: "acdsee"
a c g five: "acg"
a c k: "Ack"
a c l six: "ACL"
a c m six: "ACM"
a c n six: "ACN"
a c n t: "acnt"
a c p i: "ACPI"
a c r six: "ACR"
a c t six: "ACT"
a c t s: "ACTS"
a c t: "act"
a d d six: "ADD"
a d d r: "addr"
a d d: "add"
a d f six: "ADF"
a d f: "adf"
a d j six: "ADJ"
a d m five: "adm"
a d m six: "ADM"
a d m: "adm"
a d n six: "ADN"
a d o six: "ADO"
a d r s: "adrs"
a d s l six: "ADSL"
a d s l: "adsl"
a e six: "AE"
a f o m: "afom"
a f x: "afx"
a g l six: "AGL"
a g m six: "AGM"
a g r six: "AGR"
a h six: "AH"
a h p r a: "ahpra"
a i six: "AI"
a i d six: "AID"
a i d: "aid"
a k a: "aka"
a l b six: "ALB"
a l g six: "ALG"
a l l o c: "alloc"
a l s six: "ALS"
a l t: "alt"
a m six: "AM"
a m a s six: "AMAS"
a m i six: "AMI"
a m l six: "AML"
a m n g six: "AMNG"
a m s six: "AMS"
a m s l six: "AMSL"
a m s l: "amsl"
a n a t: "anat"
a n k i: "Anki"
a n u six: "ANU"
a n u: "Anu"
a n z six: "ANZ"
a o i six: "AOI"
a p six: "AP"
a p a six: "APA"
a p a m d u one: "ApaMdu"
a p a: "apa"
a p d u six: "APDU"
a p i six: "API"
a p i: "api"
a p p l: "appl"
a p p s: "apps"
a p p: "app"
a p t: "apt"
a q five: "aq"
a q m s six: "AQMS"
a q m s: "aqms"
a q p six: "AQP"
a q p: "aqp"
a r c: "arc"
a r g s: "Args"
a r g v: "argv"
a r g: "arg"
a r i six: "ARI"
a r n six: "ARN"
a r n: "arn"
a s c: "asc"
a s g six: "ASG"
a s m: "asm"
a s p: "asp"
a s s o c: "assoc"
a s t six: "AST"
a s t: "ast"
a s y n c: "async"
a t l five: "atl"
a t l: "ATL"
a t n: "atn"
a t o five: "ato"
a t o six: "ATO"
a t r six: "ATR"
a t r: "atr"
a t s i c six: "ATSIC"
a t t r: "attr"
a t t: "att"
a u d: "aud"
a u g: "aug"
a u s six: "AUS"
a u s t: "aust"
a u s: "aus"
a u t h: "auth"
a u t: "aut"
a v six: "AV"
a v g: "avg"
a v i one: "Avi"
a v i v i: "Avivi"
a w k: "awk"
a w s five: "aws"
a w s six: "AWS"
a w s e c two: "AWS EC2"
a w s e k s: "AWS EKS"
a w s s three: "AWS S3"
a w s: "AWS"
a x five: "ax"
a z six: "AZ"
a z o p t: "Azopt"
b a six: "BA"
b a l: "bal"
b a r e l: "Barel"
b a u d: "baud"
b b six: "BB"
b e l e l i: "beleli"
b e r: "ber"
b f six: "BF"
b i five: "bi"
b i six: "BI"
b i d a l: "BiDal"
b i n: "bin"
b i t: "bit"
b j six: "BJ"
b l a h: "blah"
b l d g: "bldg"
b l d: "bld"
b l l six: "BLL"
b l l: "bll"
b l u m: "Blum"
b o m: "bom"
b o t o three: "boto3"
b o x: "box"
b r i t: "brit"
b s p six: "BSP"
b s p: "bsp"
b s s: "bss"
b t n: "btn"
b t w six: "BTW"
b u d i: "Budi"
b u f: "buf"
b u p a: "Bupa"
b u s: "bus"
c three s: "CCcs"
c a b s: "CAbs"
c a d six: "CAD"
c a d: "cad"
c a f six: "CAF"
c a l c: "calc"
c a n n: "Cann"
c a n v a: "canva"
c a r t o: "carto"
c a s five: "cas"
c a t e g: "categ"
c a v v six: "CAVV"
c a z: "caz"
c b five: "cb"
c b a six: "CBA"
c b d six: "CBD"
c b d: "cbd"
c b f six: "CBF"
c b t: "cbt"
c c c s: "CCcs"
c c p: "CCp"
c d k six: "CDK"
c e r t: "cert"
c f five: "cf"
c f six: "CF"
c f d six: "CFD"
c f i: "cfi"
c f s six: "CFS"
c g t six: "CGT"
c h a g: "chag"
c h a i: "Chai"
c h a n i: "Chani"
c h a r s: "chars"
c h a r: "char"
c h d c six: "CHDC"
c h q: "chq"
c h r: "chr"
c h v: "chv"
c i five: "ci"
c i d: "cid"
c i t b six: "CITB"
c l six: "CL"
c l a six: "CLA"
c l a: "cla"
c l b six: "CLB"
c l b: "clb"
c l i six: "CLI"
c l i x m l: "clixml"
c l i: "cli"
c l y m: "Clym"
c m b: "cmb"
c m d: "cmd"
c m k six: "CMK"
c m p: "cmp"
c n c six: "CNC"
c n n six: "CNN"
c n t: "cnt"
c o two: "CO2"
c o five: "co"
c o a six: "COA"
c o b six: "COB"
c o c h i: "Cochi"
c o d e t: "codet"
c o h s: "COhs"
c o l s: "cols"
c o l: "col"
c o m six: "COM"
c o m b: "comb"
c o m m: "comm"
c o m: "com"
c o n d a: "conda"
c o n j: "conj"
c o n n: "conn"
c o n s: "cons"
c o n t: "cont"
c o n v: "conv"
c o n: "con"
c o o r d: "coord"
c o r p: "corp"
c o s: "cos"
c o t s six: "COTS"
c p five: "cp"
c p c s: "CpCs"
c p f d r: "CpFdr"
c p i six: "CPI"
c p s q l: "CpSql"
c p s v n: "CpSvn"
c p t six: "CPT"
c p t: "cpt"
c p y: "cpy"
c r three: "Cr"
c r n t: "crnt"
c r o n: "cron"
c r p six: "CRP"
c r s six: "CRS"
c s five: "cs"
c s a: "csa"
c s b six: "CSB"
c s p: "csp"
c s r six: "CSR"
c s s six: "CSS"
c s s: "css"
c s v: "csv"
c t six: "CT"
c t a p six: "CTAP"
c t l v: "CTlv"
c t r l: "ctrl"
c t x: "ctx"
c u f a r: "Cufar"
c u r l: "curl"
c u s t: "cust"
c v five: "cv"
c v v six: "CVV"
c v v: "cvv"
c y b g six: "CYBG"
d a five: "da"
d a six: "DA"
d a c: "dac"
d a g six: "DAG"
d a i d: "DAId"
d a l: "dal"
d a p six: "DAP"
d a r six: "DAR"
d a t: "dat"
d a x six: "DAX"
d b five: "db"
d b a: "dba"
d b o five: "dbo"
d b o: "dbo"
d b r: "dbr"
d b s: "dbs"
d c a six: "DCA"
d c d six: "DCD"
d c d: "dcd"
d d six: "DD"
d d e: "dde"
d d k: "DDK"
d d p six: "DDP"
d d r: "ddr"
d e c six: "DEC"
d e c: "dec"
d e f n: "defn"
d e f s: "defs"
d e f: "def"
d e j a i: "dejai"
d e l i m: "delim"
d e l: "del"
d e m six: "DEM"
d e m: "dem"
d e p: "dep"
d e r six: "DER"
d e s c: "Desc"
d e s t: "dest"
d e v: "dev"
d e x a six: "DEXA"
d f five: "df"
d f six: "DF"
d f c e six: "DFCE"
d f e i t: "dfeit"
d f t: "dft"
d g v: "dgv"
d h c p six: "DHCP"
d h l six: "DHL"
d i b: "DIB"
d i c t: "dict"
d i d six: "DID"
d i f f: "diff"
d i j k: "dijk"
d i m a: "Dima"
d i r s: "dirs"
d i r: "dir"
d i s p: "disp"
d i s t: "dist"
d i v: "div"
d k i m six: "DKIM"
d l g: "dlg"
d l l six: "DLL"
d l l: "dll"
d l p six: "DLP"
d m s six: "DMS"
d n seven l i b: "Dn7Lib"
d n l i b: "DnLib"
d n s six: "DNS"
d n s: "dns"
d o five: "do"
d o b six: "DOB"
d o c s: "docs"
d o c: "doc"
d o d: "dod"
d o f six: "DOF"
d o m: "dom"
d o n t: "dont"
d p i d six: "DPID"
d p i d: "dpid"
d p i: "dpi"
d q n six: "DQN"
d r five: "dr"
d r six: "DR"
d r e m e l: "dremel"
d r o r: "Dror"
d r p six: "DRP"
d r s six: "DRS"
d s l six: "DSL"
d s l a m: "dslam"
d s m six: "DSM"
d u b: "dub"
d u e: "due"
d u i: "dui"
d v d five: "dvd"
e b six: "EB"
e b s six: "EBS"
e c two six: "EC2"
e c two: "EC2"
e c six: "EC"
e c g one: "ECG-1"
e c g four: "ECG-4"
e c g six: "ECG"
e c g seven: "ECG-7"
e c g nine: "ECG-9"
e c g: "ecg"
e c r six: "ECR"
e c s six: "ECS"
e d t: "edt"
e d v six: "EDV"
e e five: "ee"
e e six: "EE"
e e a s: "eeas"
e e r: "eer"
e f five: "ef"
e f a r r: "EfArr"
e f a s: "efas"
e f d i r: "EfDir"
e f d: "efd"
e f p b r: "EfPbr"
e f s six: "EFS"
e g g: "egg"
e k g six: "EKG"
e k s six: "EKS"
e l five: "el"
e l b six: "ELB"
e l e y: "Eley"
e l i e: "Elie"
e l i: "Eli"
e l p i six: "ELPI"
e m c six: "EMC"
e m o j i: "emoji"
e m r six: "EMR"
e m r: "emr"
e n t six: "ENT"
e n t s: "ents"
e n t: "ent"
e n u m: "enum"
e n v: "env"
e o f six: "EOF"
e o f: "eof"
e o l six: "EOL"
e p l b six: "EPLB"
e p s g six: "EPSG"
e q five: "eq"
e q: "eq"
e r c p six: "ERCP"
e r e v: "erev"
e r f s: "erfs"
e r r s t r: "ErrStr"
e r r: "err"
e s a six: "ESA"
e s a: "esa"
e s r i five: "esri"
e s r i: "esri"
e t a six: "ETA"
e t f six: "ETF"
e t l six: "ETL"
e t s i six: "ETSI"
e t s i: "etsi"
e t u: "etu"
e v five: "ev"
e v six: "EV"
e v a l: "eval"
e v c three: "evc3"
e v c: "evc"
e v t: "evt"
e w k b six: "EWKB"
e x five: "ex"
e x c: "exc"
e x e c: "exec"
e x e r six: "EXER"
e x e: "exe"
e x p r: "expr"
e x p: "exp"
e x t: "ext"
e y e: "eye"
e y l o n: "Eylon"
e z six: "EZ"
f a a s: "FaaS"
f a q: "FAQ"
f a r six: "FAR"
f c p six: "FCP"
f c p: "fcp"
f c s six: "FCS"
f d six: "FD"
f d c a six: "FDCA"
f d r six: "FDR"
f d s six: "FDS"
f d s: "fds"
f e five: "fe"
f e b: "feb"
f e p six: "FEP"
f i f o six: "FIFO"
f i f o: "fifo"
f i l: "fil"
f l i r: "flir"
f l u: "flu"
f m five: "fm"
f m six: "FM"
f m e six: "FME"
f m o six: "FMO"
f m o d: "fmod"
f n five: "fn"
f n a six: "FNA"
f n n six: "FNN"
f o f i: "fofi"
f o i six: "FOI"
f o i: "foi"
f o r e: "fore"
f o r: "for"
f p five: "fp"
f p l: "fpl"
f q d n six: "FQDN"
f r e q: "freq"
f r m: "frm"
f s five: "fs"
f s a six: "FSA"
f s a m six: "FSAM"
f s a m: "fsam"
f s a: "fsa"
f s r s six: "FSRS"
f t p: "ftp"
f t t b: "fttb"
f t t c six: "FTTC"
f t t n six: "FTTN"
f t t n: "fttn"
f t t p six: "FTTP"
f t t p: "fttp"
f t t x: "fttx"
f u n c: "func"
g a six: "GA"
g a d: "gad"
g a l i a: "Galia"
g a l i t: "Galit"
g a l i: "Gali"
g b six: "GB"
g b l: "gbl"
g b: "gb"
g c five: "gc"
g c c s a: "gccsa"
g d a l six: "GDAL"
g d a l: "gdal"
g d b six: "GDB"
g d b: "gdb"
g d i five: "gdi"
g e d two: "ged2"
g e d: "ged"
g e n: "gen"
g e o c: "geoc"
g e o m: "geom"
g e o: "geo"
g f c: "gfc"
g g six: "GG"
g g a six: "GGA"
g g m six: "GGM"
g g o x six: "GGOX"
g g t six: "GGT"
g h d six: "GHD"
g h g six: "GHG"
g i five: "gi"
g i six: "GI"
g i r i: "Giri"
g i s five: "gis"
g i s six: "GIS"
g i t: "git"
g n a f six: "GNAF"
g n a f: "gnaf"
g o t o: "goto"
g o x six: "GOX"
g p two five: "gp2"
g p three five: "gp3"
g p six: "GP"
g p s five: "gps"
g p t three: "GPT-3"
g p t six: "GPT"
g r c six: "GRC"
g r d six: "GRD"
g r d: "grd"
g r e p: "grep"
g r p: "grp"
g r u six: "GRU"
g s six: "GS"
g s i six: "GSI"
g s m five: "gsm"
g s s u six: "GSSU"
g s s u: "gssu"
g s t: "GST"
g t e: "gte"
g t r six: "GTR"
g u i five: "gui"
g u i six: "GUI"
g u i d six: "GUID"
g u i: "gui"
g v x: "gvx"
g w l b six: "GWLB"
g w l: "gwl"
h a three: "Ha"
h a m a s: "Hamas"
h a t: "hat"
h c f six: "HCF"
h c t: "HCT"
h d d six: "HDD"
h d f s six: "HDFS"
h e c six: "HEC"
h e x: "hex"
h e y: "hey"
h f c six: "HFC"
h f c: "hfc"
h f l one six: "HFL1"
h f l six: "HFL"
h f l p f l three: "HflPfl"
h f l: "hfl"
h g o x six: "HGOX"
h g r: "hgr"
h h five: "hh"
h h c s: "HhCs"
h h g p s: "HhGps"
h h m: "hhm"
h h p: "hhp"
h h t t: "hhtt"
h h t: "hht"
h i n six: "HIN"
h i s t: "hist"
h m d six: "HMD"
h o u z z: "houzz"
h p c six: "HPC"
h p s six: "HPS"
h r e f: "href"
h r r l six: "HRRL"
h r r l: "hrrl"
h s l six: "HSL"
h t m l six: "HTML"
h t m l: "html"
h t t p six: "HTTP"
h t t p s six: "HTTPS"
h t t p s: "https"
h t t p: "http"
h t w six: "HTW"
h w l six: "HWL"
h w n d six: "HWND"
h x five: "hx"
i one six seven: "i167"
i a six: "IA"
i a a s: "IaaS"
i a c: "IaC"
i a m six: "IAM"
i c r six: "ICR"
i c r: "icr"
i d five: "id"
i d six: "ID"
i d d six: "IDD"
i d d: "idd"
i d e n t: "ident"
i d f six: "IDF"
i d o k: "IDOK"
i d s six: "IDS"
i d x: "idx"
i e seven: "IE7"
i g five: "ig"
i g i s: "IGis"
i g w six: "IGW"
i h h: "IHh"
i i c six: "IIC"
i i f: "iif"
i i s six: "IIS"
i l d a s m: "ildasm"
i l r six: "ILR"
i m g: "img"
i m h o six: "IMHO"
i m o six: "IMO"
i m p l: "impl"
i m u six: "IMU"
i m u t: "imut"
i n c i t s: "incits"
i n c: "inc"
i n f o: "info"
i n f: "inf"
i n g six: "ING"
i n g: "ing"
i n i t: "init"
i n m: "inm"
i n s five: "ins"
i n s six: "INS"
i n s t: "inst"
i n s: "ins"
i n t l: "intl"
i n t p t r: "IntPtr"
i n t: "int"
i o one: "io1"
i o two: "io2"
i o five: "io"
i o c: "IoC"
i o t three: "IoT"
i p five: "ip"
i p v four: "IPv4"
i p v six: "IPv6"
i q r six: "IQR"
i r p: "irp"
i s o six: "ISO"
i s o: "iso"
i s r six: "ISR"
i s r s: "ISrs"
i s r: "isr"
i t six: "IT"
i t i l six: "ITIL"
i t r o six: "ITRO"
i v l: "ivl"
i w m six: "IWM"
j a b r a: "jabra"
j a n: "jan"
j c a six: "JCA"
j e s t: "Jest"
j g six: "JG"
j i b i n: "Jibin"
j i t: "jit"
j j six: "JJ"
j l l six: "JLL"
j o n o: "Jono"
j p e g: "jpeg"
j q l: "jql"
j s five: "js"
j s o n: "json"
j t t six: "JTT"
j t t: "jtt"
j u l a i: "Julai"
j u l: "jul"
j u n: "jun"
j v six: "JV"
j w t six: "JWT"
k a f k a: "Kafka"
k b six: "KB"
k c six: "KC"
k e five: "ke"
k e m o: "kemo"
k e n n: "Kenn"
k e r a s: "keras"
k g two: "KG2"
k h six: "KH"
k i d d u s h: "kiddush"
k m five: "km"
k m l six: "KML"
k m l: "kml"
k m s six: "KMS"
k m z six: "KMZ"
k n six: "KN"
k n n six: "KNN"
k o b o: "kobo"
k p i six: "KPI"
k u b i e: "Kubie"
k u n d a n: "Kundan"
k v p six: "KVP"
k v p: "kvp"
l a h a v: "Lahav"
l a t: "lat"
l b l: "lbl"
l c s i six: "LCSI"
l e d five: "led"
l e e o r: "Leeor"
l e n: "len"
l e v i n: "Levin"
l e v y: "Levy"
l g six: "LG"
l g a six: "LGA"
l g a: "lga"
l g p s: "lgps"
l h s six: "LHS"
l i b: "lib"
l i d a r: "lidar"
l i n q: "linq"
l k six: "LK"
l l five: "ll"
l m five: "lm"
l m s six: "LMS"
l o a: "LoA"
l o c: "loc"
l o l: "lol"
l o s three: "LoS"
l o s six: "LOS"
l o s: "los"
l p six: "LP"
l p c s t r: "LPCSTR"
l p g s six: "LPGS"
l p t one: "LPT1"
l p w s t r: "LPWSTR"
l s five: "ls"
l s i six: "LSI"
l s p: "lsp"
l s t m six: "LSTM"
l s t p: "lstp"
l s t: "lst"
l t d three: "Ltd"
l t e: "lte"
l t r six: "LTR"
l t r: "ltr"
l t s six: "LTS"
l y n x: "lynx"
m two: "m2"
m a six: "MA"
m a c: "mac"
m a p i five: "mapi"
m a p i: "MAPI"
m a r: "mar"
m a t h: "math"
m a x i: "maxi"
m b five: "mb"
m c g: "mcg"
m c q six: "MCQ"
m d b six: "MDB"
m d b: "mdb"
m d m six: "MDM"
m d u six: "MDU"
m d u: "mdu"
m e d: "med"
m e m: "mem"
m e r six: "MER"
m e r a v: "Merav"
m e s s: "mess"
m e x: "mex"
m f five: "mf"
m f six: "MF"
m f a six: "MFA"
m f a: "mfa"
m f c: "mfc"
m g r: "mgr"
m i c h a l: "Michal"
m i d: "mid"
m i f: "mif"
m i g: "mig"
m i m e: "mime"
m i n a: "Mina"
m i n y a n: "minyan"
m i n: "min"
m i o: "Mio"
m i s c: "misc"
m i y a: "Miya"
m l six: "ML"
m l c six: "MLC"
m m five: "mm"
m m six: "MM"
m m c: "mmc"
m m o six: "MMO"
m m o: "mmo"
m m s six: "MMS"
m m: "mm"
m o d: "mod"
m p three: "mp3"
m q t six: "MQT"
m q t t six: "MQTT"
m r i six: "MRI"
m r p six: "MRP"
m r p: "mrp"
m r r six: "MRR"
m r r p six: "MRRP"
m r r: "mrr"
m r u: "mru"
m s five: "ms"
m s a six: "MSA"
m s b six: "MSB"
m s d n: "MSDN"
m s g: "msg"
m s i: "msi"
m s k six: "MSK"
m s m six: "MSM"
m s v c: "msvc"
m t c f six: "MTCF"
m t m: "mtm"
m t o six: "MTO"
m u five: "mu"
m u k u l: "Mukul"
m v c six: "MVC"
m v c: "mvc"
m w s six: "MWS"
m w s: "mws"
m z six: "MZ"
n a five: "na"
n a b six: "NAB"
n a b: "NAB"
n a c l six: "NACL"
n a n g: "Nang"
n a t six: "NAT"
n a t: "nat"
n a v: "nav"
n b six: "NB"
n b n six: "NBN"
n b n e e one: "NbnEe"
n b n p o i: "NbnPoi"
n b n: "nbn"
n b r: "nbr"
n c h six: "NCH"
n e e r a j: "Neeraj"
n e f o six: "NEFO"
n e f o: "nefo"
n e t six: "NET"
n f s six: "NFS"
n g r o k: "ngrok"
n i k u d: "nikud"
n i l y: "Nily"
n i t e: "nite"
n l b six: "NLB"
n l p six: "NLP"
n l p: "nlp"
n l t: "nlt"
n m b six: "NMB"
n m b l: "nmbl"
n m e a: "nmea"
n n six: "NN"
n o r m: "norm"
n o v: "nov"
n p m: "npm"
n p o s: "npos"
n s five: "ns"
n s w six: "NSW"
n t five: "nt"
n t six: "NT"
n u m: "num"
n v a r: "nvar"
n z five: "nz"
o a six: "OA"
o a c six: "OAC"
o a i six: "OAI"
o a u t h: "OAuth"
o b i e: "Obie"
o b j: "obj"
o c i six: "OCI"
o c r six: "OCR"
o c t six: "OCT"
o c t: "oct"
o d b c six: "ODBC"
o d b c: "odbc"
o d i: "Odi"
o f a s six: "OFAS"
o f a s: "ofas"
o f e r: "Ofer"
o f f: "off"
o g m six: "OGM"
o g r six: "OGR"
o g r: "ogr"
o h a n a: "Ohana"
o h s: "ohs"
o k five: "ok"
o k six: "OK"
o l a p six: "OLAP"
o l e: "ole"
o l y a: "Olya"
o m e o: "Omeo"
o m g six: "OMG"
o n c: "onc"
o o i: "Ooi"
o o m six: "OOM"
o p five: "op"
o p g six: "OPG"
o p s six: "OPS"
o p s: "ops"
o p t i: "opti"
o r c six: "ORC"
o r g: "org"
o r i g: "orig"
o s five: "os"
o s f six: "OSF"
o s f: "osf"
o s g e o: "OSGeo"
o s i six: "OSI"
o s i: "osi"
o s r six: "OSR"
o s r r: "osrr"
o s r: "osr"
o t six: "OT"
o t p six: "OTP"
o t t six: "OTT"
o z: "oz"
p one three three: "p133"
p one six: "P1"
p a a g e: "paage"
p a a l: "paal"
p a a s: "PaaS"
p a f six: "PAF"
p a f: "paf"
p a p s six: "PAPS"
p a r a m s: "params"
p a r a m: "param"
p a r a: "para"
p a r e n: "paren"
p b five: "pb"
p b six: "PB"
p b e six: "PBE"
p b e: "pbe"
p b r six: "PBR"
p c a six: "PCA"
p c h: "pch"
p d f six: "PDF"
p d f: "pdf"
p d p six: "PDP"
p d s six: "PDS"
p e l: "pEl"
p e m six: "PEM"
p e m: "pem"
p e n: "pen"
p e r f: "perf"
p e r i s: "Peris"
p e r p: "perp"
p e r: "per"
p f a r six: "PFAR"
p f a r: "pfar"
p f l six: "PFL"
p f l: "pfl"
p f x six: "PFX"
p g c six: "PGC"
p g p six: "PGP"
p h e t: "phet"
p i d six: "PID"
p i d s: "PIDs"
p i d: "pid"
p i i six: "PII"
p i m six: "PIM"
p i n six: "PIN"
p i n v: "pinv"
p i n: "pin"
p i p u six: "PIPU"
p i p u: "pipu"
p i p: "pip"
p i x: "pix"
p l t: "plt"
p m t: "pmt"
p n g six: "PNG"
p n p six: "PNP"
p n p m: "pnpm"
p n p: "pnp"
p o a six: "POA"
p o i six: "POI"
p o i: "poi"
p o l y: "poly"
p o r n: "porn"
p o s six: "POS"
p o s: "pos"
p p c six: "PPC"
p p c: "ppc"
p p m: "ppm"
p p w: "ppw"
p r six s: "PRs"
p r six: "PR"
p r e p: "prep"
p r e v: "prev"
p r e: "pre"
p r o c: "proc"
p r o d: "prod"
p r o g: "prog"
p r o j c s: "ProjCS"
p r o j: "proj"
p r o n six: "PRON"
p r o p: "prop"
p r o t o: "proto"
p r o v: "prov"
p r o: "pro"
p r s six: "PRS"
p r s: "prs"
p s one: "ps1"
p s m a six: "PSMA"
p s v six: "PSV"
p s v: "psv"
p t r: "ptr"
p t y three: "Pty"
p u r i m: "Purim"
p w d: "pwd"
p w t six: "PWT"
q two: "Q2"
q three: "Q3"
q four: "Q4"
q a n d a: "qanda"
q a s: "qas"
q g i s six: "QGIS"
q l d six: "QLD"
q l d: "qld"
q t y: "qty"
q u e: "Que"
q u i p: "Quip"
r a five: "ra"
r a six: "RA"
r a c: "rac"
r a n d: "rand"
r a p six: "RAP"
r a p: "rap"
r a z: "raz"
r b b p six: "RBBP"
r b s six: "RBS"
r c s: "rcs"
r c u six: "RCU"
r d a r: "rdar"
r d d six: "RDD"
r d f six: "RDF"
r d p six: "RDP"
r d p: "rdp"
r d r: "rdr"
r d s six: "RDS"
r d s: "rds"
r e c: "rec"
r e d i s: "Redis"
r e f: "ref"
r e g e x: "regex"
r e l: "rel"
r e m: "rem"
r e p o: "repo"
r e p: "rep"
r e s i: "resi"
r e s p: "resp"
r e s: "res"
r e t: "ret"
r f i six: "RFI"
r f i: "rfi"
r f s six: "RFS"
r g n six: "RGN"
r h s six: "RHS"
r i a a six: "RIAA"
r i l: "ril"
r i m: "rim"
r j z: "rjz"
r m c six: "RMC"
r m s six: "RMS"
r n d: "rnd"
r n n six: "RNN"
r o k: "rok"
r o l y: "roly"
r o n e n: "Ronen"
r o n i: "Roni"
r o n q: "ronq"
r o s six: "ROS"
r p o six: "RPO"
r r i six: "RRI"
r s six: "RS"
r s t: "rst"
r s v p: "rsvp"
r t a: "RTA"
r t c six: "RTC"
r t l six: "RTL"
r t l: "rtl"
r t s six: "RTS"
r x three: "Rx"
r x five: "rx"
r z two six: "RZ2"
r z six: "RZ"
s three d: "S3d"
s three: "S3"
s a one five: "sa1"
s a one: "SA1"
s a two five: "sa2"
s a two six: "SA2"
s a three five: "sa3"
s a four five: "sa4"
s a five: "sa"
s a six: "SA"
s a a s: "SaaS"
s a m e a c h: "sameach"
s a m l six: "SAML"
s a n six: "SAN"
s a n u s: "Sanus"
s a r six: "SAR"
s a r i f: "sarif"
s a r u s h: "Sarush"
s a v t a: "Savta"
s a x: "sax"
s a: "sa"
s b five: "sb"
s b s six: "SBS"
s c one five: "sc1"
s c five: "sc"
s c six: "SC"
s c a: "sca"
s c h e d: "sched"
s c m six: "SCM"
s c o s: "scos"
s c p six: "SCP"
s c t six: "SCT"
s c t: "sct"
s d e six: "SDE"
s d i six: "SDI"
s d k: "SDK"
s d n six: "SDN"
s d u six: "SDU"
s e five: "se"
s e c: "sec"
s e d e r: "Seder"
s e e e d: "seeed"
s e i d six: "SEID"
s e l: "sel"
s e p three: "Sep"
s e p: "sep"
s e q: "seq"
s e s six: "SES"
s f five: "sf"
s f six: "SF"
s f c: "sfc"
s f i six: "SFI"
s f t p six: "SFTP"
s f t p: "sftp"
s g s six: "SGS"
s h three: "sh3"
s h a h a r: "Shahar"
s h p: "shp"
s h u l a: "Shula"
s h u l: "Shul"
s i five: "si"
s i m six: "SIM"
s i n: "sin"
s j m six: "SJM"
s l a six: "SLA"
s l a a: "slaa"
s l r six: "SLR"
s l t six: "SLT"
s m s six: "SMS"
s m t p six: "SMTP"
s m t p: "smtp"
s n e h a l: "Snehal"
s n g: "sng"
s n s six: "SNS"
s n s: "sns"
s o a six: "SOA"
s o c three: "SoC"
s o f six: "SOF"
s o h o six: "SOHO"
s o n o s: "sonos"
s o w six: "SOW"
s p five: "sp"
s p six: "SP"
s p eight three five three six: "SP8535"
s p a six: "SPA"
s p a h r: "Spahr"
s p c: "spc"
s p e c: "spec"
s p o f: "spof"
s q k m: "sqkm"
s q l five: "sql"
s q l six: "SQL"
s q l: "sql"
s q m: "sqm"
s q r t: "sqrt"
s q r: "sqr"
s q s six: "SQS"
s r five: "sr"
s r six: "SR"
s r c: "src"
s r i d six: "SRID"
s r i d: "srid"
s r n six: "SRN"
s r s: "srs"
s r t six: "SRT"
s r t: "srt"
s r v r: "srvr"
s s a six: "SSA"
s s d one six: "SSD1"
s s d six: "SSD"
s s h six: "SSH"
s s i s six: "SSIS"
s s l six: "SSL"
s s m six: "SSM"
s s o six: "SSO"
s s s six: "SSS"
s s s a: "sssa"
s s s c p s v: "ssscpsv"
s s s: "sss"
s t a t s: "stats"
s t a t: "stat"
s t d six: "STD"
s t d: "std"
s t g six: "STG"
s t l six: "STL"
s t p: "stp"
s t r: "str"
s t s six: "STS"
s t x six: "STX"
s u b l: "subl"
s u m r a: "Sumra"
s u m: "sum"
s u p six: "SUP"
s u p: "sup"
s v c: "svc"
s v d six: "SVD"
s v h six: "SVH"
s v n six: "SVN"
s v n: "svn"
s v r: "svr"
s w two: "SW2"
s w five: "sw"
s w f six: "SWF"
s w l: "swl"
s y g i c: "sygic"
s y n c: "sync"
s y s: "sys"
t a b: "tab"
t a n a: "Tana"
t a p o: "Tapo"
t a s six: "TAS"
t a u: "tau"
t b d six: "TBD"
t b l: "tbl"
t c n: "tcn"
t c p five: "tcp"
t d five: "td"
t d six: "TD"
t e c h: "tech"
t e m p: "temp"
t f six: "TF"
t f n six: "TFN"
t h c: "thc"
t h x: "thx"
t i five: "ti"
t i f: "tif"
t l s six: "TLS"
t l s: "tls"
t l v six: "TLV"
t m j six: "TMJ"
t m n e: "Tmne"
t m p: "Tmp"
t n r d six: "TNRD"
t n t five: "tnt"
t n t six: "TNT"
t o five: "to"
t o b y: "Toby"
t o c six: "TOC"
t o d o: "todo"
t o f: "tof"
t o g g l: "toggl"
t o n six: "TON"
t o o: "too"
t o p o: "topo"
t o t p six: "TOTP"
t p d six: "TPD"
t p g six: "TPG"
t p g c six: "TPGC"
t p g c: "tpgc"
t p s c: "tpsc"
t p s: "tps"
t p t: "tpt"
t p u six: "TPU"
t r a n s: "trans"
t s five: "ts"
t s six: "TS"
t s c: "tsc"
t s t: "tst"
t s v: "tsv"
t t i: "tti"
t t l six: "TTL"
t t n c f: "ttncf"
t t n: "ttn"
t t p six: "TTP"
t t s s six: "TTSS"
t u i: "tui"
t w o: "two"
t x three: "Tx"
t x five: "tx"
t x t: "txt"
u a f six: "UAF"
u c c six: "UCC"
u c l six: "UCL"
u c l: "ucl"
u d f six: "UDF"
u d f: "udf"
u d p six: "UDP"
u i five: "ui"
u i six: "UI"
u i c c five: "uicc"
u i c c six: "UICC"
u i n t: "UInt"
u m l six: "UML"
u n r w a: "unrwa"
u p a one: "UPA1"
u p a six: "UPA"
u p a g s one: "UpaGs"
u p a: "upa"
u p s six: "UPS"
u r five: "ur"
u r b: "urb"
u r i: "uri"
u r l six: "URL"
u r l s: "urls"
u r l: "url"
u s five: "us"
u s b six: "USB"
u s b: "usb"
u s i d: "usid"
u s i m: "USIM"
u t c six: "UTC"
u t f: "utf"
u t i l s: "utils"
u t i l: "util"
u t l: "utl"
u w p: "uwp"
v one five zero: "v1.5.0"
v one one one: "v1.1.1"
v one four zero: "v1.4.0"
v five: "v5"
v a six: "VA"
v a l: "val"
v a r: "var"
v b five: "vb"
v b six: "VB"
v b a six: "VBA"
v c six: "VC"
v c c six: "VCC"
v c c: "vcc"
v c p u: "vCPU"
v d s l six: "VDSL"
v e n n: "venn"
v e n v: "venv"
v e r: "ver"
v g w six: "VGW"
v i c six: "VIC"
v i c: "vic"
v i p six: "VIP"
v m six: "VM"
v m c six: "VMC"
v m x six: "VMX"
v m z: "VMs"
v n c: "vnc"
v o c u s: "Vocus"
v o i p: "VoIP"
v o n e x: "Vonex"
v p c six: "VPC"
v p c: "vpc"
v p n six: "VPN"
v r six: "VR"
v s five: "vs"
v s six: "VS"
v s s: "vss"
v s x f l: "VsXfl"
v t l six: "VTL"
v x d six: "VXD"
w three w p: "w3wp"
w a six: "WA"
w a f six: "WAF"
w a h l: "Wahl"
w a n six: "WAN"
w a q six: "WAQ"
w a q: "waq"
w c f six: "WCF"
w c f: "wcf"
w c u six: "WCU"
w d m: "WDM"
w e s six: "WES"
w e s: "wes"
w f four: "WF4"
w g s six: "WGS"
w h q l: "WHQL"
w i k i: "wiki"
w i x: "wix"
w k b six: "WKB"
w k t six: "WKT"
w k t: "wkt"
w l six: "WL"
w m e: "wme"
w m f: "wmf"
w m p c f: "WmpCf"
w m p: "wmp"
w m s: "wms"
w n d: "wnd"
w o n: "Won"
w o t i f: "Wotif"
w o w six: "WOW"
w p f six: "WPF"
w p o i six: "WPOI"
w p p w: "wppw"
w s five: "ws"
w s a six: "WSA"
w s g six: "WSG"
w s g: "wsg"
w w w: "www"
x a m l six: "XAML"
x a m l: "xaml"
x d o c: "xdoc"
x d s l: "xdsl"
x f l six: "XFL"
x f l: "xfl"
x l s x: "xlsx"
x l s: "xls"
x m l five: "xml"
x m l six: "XML"
x o d o: "xodo"
x p six: "XP"
x p s: "xps"
x s d six: "XSD"
x s d: "xsd"
x x x six: "XXX"
x y: "xy"
y two k: "Y2K"
y a six: "YA"
y a m l six: "YAML"
y a m l: "yaml"
y a r d e n: "Yarden"
y c l: "ycl"
y h a t: "yhat"
y i e n: "Yien"
y o s i: "Yosi"
y u v i: "Yuvi"
y y six: "YY"
y y y y: "yyyy"
z o h o: "Zoho"
z t e six: "ZTE"
z u l: "zul"
p i p u six: "PIPU"